import type { AppData } from '../types';
import { daily, makeWave } from './shared';

/** Демо-пространство «DIY» — сеть строительных гипермаркетов «Мастерский». */
export function diySpace(): AppData {
  return {
    space: 'diy',
    company: {
      id: 'd1',
      name: 'Мастерский',
      industry: 'diy',
      staffSize: '200–500',
      pointsPlanned: '3',
      city: 'Екатеринбург',
      joinCode: 'MASTERSKY-2026',
      createdAt: '2026-04-10',
    },
    points: [
      {
        id: 'm1',
        name: 'Мастерский Юг',
        city: 'Екатеринбург',
        address: 'ул. Щербакова, 4',
        zones: ['Отделка', 'Инструмент', 'Сантехника', 'Склад'],
        manager: 'Виктор Пахомов',
        staffCount: 3,
        badgesOnline: 2,
        plan: 18_500_000,
        revenue: 19_240_000,
        avgCheck: 8_640,
        interactions: 2228,
        conversion: 31.4,
        scriptCompliance: 82,
        training: 81,
        helpRequests: 386,
        industry: {
          pickAccuracy: 88,
          compatQuestions: 412,
          specialistEscalations: 218,
          wrongAdvice: 34,
          stockQueries: 486,
          companionSales: 44,
        },
      },
      {
        id: 'm2',
        name: 'Мастерский Север',
        city: 'Екатеринбург',
        address: 'пр. Космонавтов, 92',
        zones: ['Отделка', 'Крепёж', 'Склад'],
        manager: 'Лариса Гимадиева',
        staffCount: 2,
        badgesOnline: 2,
        plan: 14_200_000,
        revenue: 12_360_000,
        avgCheck: 7_120,
        interactions: 1736,
        conversion: 24.8,
        scriptCompliance: 71,
        training: 58,
        helpRequests: 512,
        industry: {
          pickAccuracy: 72,
          compatQuestions: 388,
          specialistEscalations: 341,
          wrongAdvice: 76,
          stockQueries: 402,
          companionSales: 26,
        },
      },
      {
        id: 'm3',
        name: 'Мастерский Тюмень',
        city: 'Тюмень',
        address: 'ул. Федюнинского, 62',
        zones: ['Отделка', 'Инструмент', 'Сад'],
        manager: 'Игорь Севастьянов',
        staffCount: 2,
        badgesOnline: 1,
        plan: 11_800_000,
        revenue: 12_014_000,
        avgCheck: 8_180,
        interactions: 1469,
        conversion: 29.6,
        scriptCompliance: 84,
        training: 88,
        helpRequests: 241,
        industry: {
          pickAccuracy: 90,
          compatQuestions: 264,
          specialistEscalations: 132,
          wrongAdvice: 21,
          stockQueries: 318,
          companionSales: 48,
        },
      },
    ],
    accounts: [
      {
        id: 'da1',
        role: 'rop',
        name: 'Виктор Пахомов',
        email: 'rop@mastersky.ru',
        password: 'onvy2026',
        companyId: 'd1',
        position: 'Операционный директор',
        focus: 'operations',
      },
      {
        id: 'da2',
        role: 'employee',
        name: 'Сергей Демидов',
        email: 'sergey@mastersky.ru',
        password: 'onvy2026',
        companyId: 'd1',
        pointId: 'm1',
        position: 'Специалист отдела',
        employeeId: 'q1',
      },
    ],
    employees: [
      {
        id: 'q1',
        name: 'Сергей Демидов',
        position: 'Специалист отдела',
        pointId: 'm1',
        hiredAt: '2023-08-14',
        onboarding: 100,
        level: 8,
        xp: 7240,
        badgeOnline: true,
        badgeBattery: 74,
        micQuality: 92,
        stats: {
          revenue: 8_120_000,
          deals: 412,
          dialogs: 968,
          avgCheck: 19_708,
          conversion: 42.6,
          scriptCompliance: 93,
          responseSec: 3.4,
          autonomy: 94,
          helpRequests: 48,
        },
        industry: {
          pickAccuracy: 96,
          compatQuestions: 168,
          specialistEscalations: 12,
          wrongAdvice: 3,
          stockQueries: 194,
          companionSales: 61,
        },
        daily: daily(11, 580_000),
        topItems: [
          { name: 'Штукатурка гипсовая, 30 кг', qty: 486, revenue: 2_186_000 },
          { name: 'Грунтовка глубокого проникновения', qty: 312, revenue: 624_000 },
          { name: 'Профиль потолочный', qty: 894, revenue: 1_072_000 },
          { name: 'Крепёж и расходники', qty: 1240, revenue: 372_000 },
        ],
        topRequests: [
          { label: 'Какую грунтовку взять под эту штукатурку?', count: 168, conversion: 64 },
          { label: 'Сколько мешков нужно на комнату?', count: 142, conversion: 71 },
          { label: 'Это подойдёт для влажного помещения?', count: 96, conversion: 58 },
          { label: 'Есть ли это на складе?', count: 194, conversion: 49 },
        ],
        strengths: [
          'Всегда уточняет основание и условия работ до подбора материала',
          'Считает расход при клиенте — сопутствующие материалы уходят в 61 % чеков',
          'Три ошибки в рекомендациях за месяц при среднем по сети 44',
        ],
        growthAreas: ['Иногда уходит в лишние технические детали — консультации длиннее нормы на 3 минуты'],
        trainingDone: 3,
        trainingTotal: 3,
      },
      {
        id: 'q2',
        name: 'Наталья Ковалёва',
        position: 'Продавец-консультант',
        pointId: 'm1',
        hiredAt: '2025-06-01',
        onboarding: 100,
        level: 5,
        xp: 3860,
        badgeOnline: true,
        badgeBattery: 58,
        micQuality: 87,
        stats: {
          revenue: 6_240_000,
          deals: 348,
          dialogs: 762,
          avgCheck: 17_931,
          conversion: 45.7,
          scriptCompliance: 84,
          responseSec: 4.2,
          autonomy: 82,
          helpRequests: 96,
        },
        industry: {
          pickAccuracy: 86,
          compatQuestions: 132,
          specialistEscalations: 64,
          wrongAdvice: 11,
          stockQueries: 168,
          companionSales: 42,
        },
        daily: daily(22, 446_000),
        topItems: [
          { name: 'Ламинат 33 класс', qty: 1_840, revenue: 2_760_000 },
          { name: 'Подложка под ламинат', qty: 920, revenue: 368_000 },
          { name: 'Плинтус напольный', qty: 640, revenue: 256_000 },
        ],
        topRequests: [
          { label: 'Сколько мешков нужно на комнату?', count: 118, conversion: 68 },
          { label: 'Это подойдёт для влажного помещения?', count: 88, conversion: 54 },
          { label: 'Какую грунтовку взять под эту штукатурку?', count: 64, conversion: 51 },
        ],
        strengths: ['Отлично считает расход по напольным покрытиям', 'Подложка и плинтус уходят почти всегда'],
        growthAreas: [
          'Влажные помещения: 64 обращения к специалисту вместо базы знаний',
          '11 ошибок в рекомендациях по совместимости за месяц',
        ],
        trainingDone: 2,
        trainingTotal: 3,
      },
      {
        id: 'q3',
        name: 'Артур Бикмуллин',
        position: 'Стажёр',
        pointId: 'm1',
        hiredAt: '2026-07-01',
        onboarding: 52,
        level: 2,
        xp: 840,
        badgeOnline: false,
        badgeBattery: 16,
        micQuality: 72,
        stats: {
          revenue: 2_180_000,
          deals: 142,
          dialogs: 498,
          avgCheck: 15_352,
          conversion: 28.5,
          scriptCompliance: 62,
          responseSec: 9.6,
          autonomy: 44,
          helpRequests: 142,
        },
        industry: {
          pickAccuracy: 64,
          compatQuestions: 112,
          specialistEscalations: 142,
          wrongAdvice: 20,
          stockQueries: 124,
          companionSales: 18,
        },
        daily: daily(33, 156_000),
        topItems: [
          { name: 'Краска интерьерная', qty: 268, revenue: 938_000 },
          { name: 'Валики и кисти', qty: 412, revenue: 164_000 },
        ],
        topRequests: [
          { label: 'Какую грунтовку взять под эту штукатурку?', count: 112, conversion: 22 },
          { label: 'Это подойдёт для влажного помещения?', count: 76, conversion: 19 },
        ],
        strengths: ['Внимателен к клиенту, не бросает вопрос без ответа'],
        growthAreas: [
          'Не уточняет основание перед подбором — 20 ошибочных рекомендаций за месяц',
          '142 обращения к специалисту: почти каждый второй вопрос уходит наверх',
          'Не считает расход, поэтому клиент возвращается за добавкой',
        ],
        trainingDone: 0,
        trainingTotal: 3,
      },
      {
        id: 'q4',
        name: 'Лариса Гимадиева',
        position: 'Специалист отдела',
        pointId: 'm2',
        hiredAt: '2024-02-19',
        onboarding: 100,
        level: 6,
        xp: 5120,
        badgeOnline: true,
        badgeBattery: 63,
        micQuality: 89,
        stats: {
          revenue: 7_180_000,
          deals: 402,
          dialogs: 894,
          avgCheck: 17_860,
          conversion: 45.0,
          scriptCompliance: 86,
          responseSec: 3.8,
          autonomy: 87,
          helpRequests: 112,
        },
        industry: {
          pickAccuracy: 88,
          compatQuestions: 186,
          specialistEscalations: 78,
          wrongAdvice: 14,
          stockQueries: 212,
          companionSales: 38,
        },
        daily: daily(44, 512_000),
        topItems: [
          { name: 'Плитка керамическая', qty: 2_140, revenue: 3_210_000 },
          { name: 'Клей плиточный', qty: 486, revenue: 583_000 },
          { name: 'Затирка для швов', qty: 312, revenue: 218_000 },
        ],
        topRequests: [
          { label: 'Какой клей для этой плитки?', count: 186, conversion: 62 },
          { label: 'Это подойдёт для влажного помещения?', count: 124, conversion: 57 },
          { label: 'Есть ли это на складе?', count: 212, conversion: 44 },
        ],
        strengths: ['Сильна в плиточных работах: клей и затирка почти всегда в чеке'],
        growthAreas: ['Не всегда предупреждает о времени высыхания — часть клиентов возвращается с претензией'],
        trainingDone: 3,
        trainingTotal: 3,
      },
      {
        id: 'q5',
        name: 'Павел Мещеряков',
        position: 'Продавец-консультант',
        pointId: 'm2',
        hiredAt: '2025-10-07',
        onboarding: 84,
        level: 4,
        xp: 2640,
        badgeOnline: true,
        badgeBattery: 41,
        micQuality: 80,
        stats: {
          revenue: 5_180_000,
          deals: 268,
          dialogs: 842,
          avgCheck: 19_328,
          conversion: 31.8,
          scriptCompliance: 68,
          responseSec: 7.4,
          autonomy: 61,
          helpRequests: 264,
        },
        industry: {
          pickAccuracy: 66,
          compatQuestions: 202,
          specialistEscalations: 263,
          wrongAdvice: 62,
          stockQueries: 190,
          companionSales: 20,
        },
        daily: daily(55, 370_000),
        topItems: [
          { name: 'Смеси для стяжки', qty: 620, revenue: 1_860_000 },
          { name: 'Гидроизоляция', qty: 184, revenue: 736_000 },
        ],
        topRequests: [
          { label: 'Какую грунтовку взять под эту штукатурку?', count: 158, conversion: 28 },
          { label: 'Это подойдёт для влажного помещения?', count: 202, conversion: 24 },
        ],
        strengths: ['Не боится сложных заказов по объёму'],
        growthAreas: [
          '62 ошибки в рекомендациях — худший показатель сети. Причина: подбор без уточнения основания.',
          '263 обращения к специалисту вместо базы совместимости',
          'Сопутствующие материалы предлагает в 20 % чеков при норме 44 %',
        ],
        trainingDone: 1,
        trainingTotal: 3,
      },
      {
        id: 'q6',
        name: 'Игорь Севастьянов',
        position: 'Специалист отдела',
        pointId: 'm3',
        hiredAt: '2024-05-30',
        onboarding: 100,
        level: 6,
        xp: 4980,
        badgeOnline: true,
        badgeBattery: 69,
        micQuality: 90,
        stats: {
          revenue: 6_940_000,
          deals: 386,
          dialogs: 812,
          avgCheck: 17_979,
          conversion: 47.5,
          scriptCompliance: 90,
          responseSec: 3.5,
          autonomy: 91,
          helpRequests: 68,
        },
        industry: {
          pickAccuracy: 93,
          compatQuestions: 148,
          specialistEscalations: 32,
          wrongAdvice: 8,
          stockQueries: 176,
          companionSales: 54,
        },
        daily: daily(66, 496_000),
        topItems: [
          { name: 'Пиломатериалы', qty: 1_680, revenue: 2_520_000 },
          { name: 'Крепёж и метизы', qty: 2_140, revenue: 642_000 },
          { name: 'Пропитка для дерева', qty: 286, revenue: 429_000 },
        ],
        topRequests: [
          { label: 'Чем обработать дерево на улице?', count: 148, conversion: 66 },
          { label: 'Сколько мешков нужно на комнату?', count: 96, conversion: 62 },
        ],
        strengths: ['Лучшая точность подбора в сети — 93 %', 'Всегда предупреждает о технике безопасности'],
        growthAreas: ['Мало работает с крупными заказами под доставку'],
        trainingDone: 3,
        trainingTotal: 3,
      },
      {
        id: 'q7',
        name: 'Динара Хафизова',
        position: 'Продавец-консультант',
        pointId: 'm3',
        hiredAt: '2026-02-16',
        onboarding: 76,
        level: 3,
        xp: 1740,
        badgeOnline: false,
        badgeBattery: 4,
        micQuality: 74,
        stats: {
          revenue: 5_074_000,
          deals: 249,
          dialogs: 657,
          avgCheck: 20_378,
          conversion: 37.9,
          scriptCompliance: 78,
          responseSec: 5.8,
          autonomy: 70,
          helpRequests: 173,
        },
        industry: {
          pickAccuracy: 80,
          compatQuestions: 116,
          specialistEscalations: 100,
          wrongAdvice: 13,
          stockQueries: 142,
          companionSales: 34,
        },
        daily: daily(77, 362_000),
        topItems: [
          { name: 'Садовый инструмент', qty: 486, revenue: 1_458_000 },
          { name: 'Грунт и удобрения', qty: 892, revenue: 624_000 },
        ],
        topRequests: [
          { label: 'Это подойдёт для влажного помещения?', count: 116, conversion: 41 },
          { label: 'Есть ли это на складе?', count: 142, conversion: 46 },
        ],
        strengths: ['Хорошо ориентируется в садовом сезоне'],
        growthAreas: ['Совместимость материалов — 100 обращений к специалисту за месяц'],
        trainingDone: 1,
        trainingTotal: 3,
      },
    ],
    kpis: [
      { id: 'dk1', employeeId: 'q1', metric: 'revenue', target: 8_000_000, current: 8_120_000, period: 'month', setBy: 'Виктор Пахомов' },
      { id: 'dk2', employeeId: 'q1', metric: 'companionSales', target: 55, current: 61, period: 'week', setBy: 'Виктор Пахомов' },
      { id: 'dk3', employeeId: 'q2', metric: 'pickAccuracy', target: 90, current: 86, period: 'week', setBy: 'Виктор Пахомов' },
      { id: 'dk4', employeeId: 'q3', metric: 'wrongAdvice', target: 8, current: 20, period: 'month', setBy: 'Виктор Пахомов', note: 'Сначала основание и условия, потом материал' },
      { id: 'dk5', employeeId: 'q3', metric: 'autonomy', target: 65, current: 44, period: 'week', setBy: 'Виктор Пахомов', note: 'Совместимость есть в базе — смотрим там' },
      { id: 'dk6', employeeId: 'q3', metric: 'scriptCompliance', target: 80, current: 62, period: 'week', setBy: 'Виктор Пахомов' },
      { id: 'dk7', employeeId: 'q4', metric: 'revenue', target: 7_000_000, current: 7_180_000, period: 'month', setBy: 'Виктор Пахомов' },
      { id: 'dk8', employeeId: 'q5', metric: 'wrongAdvice', target: 20, current: 62, period: 'month', setBy: 'Виктор Пахомов', note: 'Критично: ошибка в подборе возвращается рекламацией' },
      { id: 'dk9', employeeId: 'q5', metric: 'companionSales', target: 40, current: 20, period: 'week', setBy: 'Виктор Пахомов' },
      { id: 'dk10', employeeId: 'q6', metric: 'revenue', target: 6_800_000, current: 6_940_000, period: 'month', setBy: 'Виктор Пахомов' },
      { id: 'dk11', employeeId: 'q7', metric: 'specialistEscalations', target: 50, current: 100, period: 'month', setBy: 'Виктор Пахомов' },
    ],
    dialogs: [
      {
        id: 'dd1',
        employeeId: 'q3',
        pointId: 'm1',
        startedAt: '2026-07-29T12:40:00',
        durationSec: 468,
        outcome: 'lost',
        revenue: 0,
        scriptScore: 48,
        responseSec: 11.2,
        category: 'Совместимость',
        topic: 'Грунтовка под штукатурку',
        items: [],
        helpRequests: 2,
        hasCue: true,
        wave: makeWave(801),
        moments: [
          { id: 'dm1', at: 11, type: 'miss', title: 'Не уточнил основание', note: 'Подбор грунтовки начат без вопроса о материале стены. Дальше вся рекомендация строилась на догадке.' },
          { id: 'dm2', at: 34, type: 'miss', title: 'Рекомендовал несовместимый состав', note: 'Универсальная грунтовка на газобетон не удержит гипсовую штукатурку — это рекламация.' },
          { id: 'dm3', at: 52, type: 'help', title: 'Позвал специалиста отдела', note: 'Обращение после того, как клиент усомнился. Ожидание — 2 минуты.' },
          { id: 'dm4', at: 78, type: 'miss', title: 'Не рассчитал объём', note: 'Клиент ушёл считать сам. Без расчёта нет сопутствующих материалов и нет сделки.' },
        ],
        transcript: [
          { id: 'dt1', at: 10, speaker: 'client', text: 'Мне нужна грунтовка, буду штукатурить стены гипсовой смесью.' },
          { id: 'dt2', at: 18, speaker: 'employee', text: 'Вот универсальная, берут чаще всего.', momentId: 'dm1' },
          { id: 'dt3', at: 26, speaker: 'ai', text: 'Подсказка: уточните основание. Для газобетона и других пористых оснований нужна грунтовка глубокого проникновения, универсальная не подойдёт.' },
          { id: 'dt4', at: 96, speaker: 'client', text: 'А у меня газобетон. Точно эта подойдёт?' },
          { id: 'dt5', at: 108, speaker: 'employee', text: 'Думаю, да, она универсальная.', momentId: 'dm2' },
          { id: 'dt6', at: 118, speaker: 'ai', text: 'Информация не подтверждена. Универсальная грунтовка не рекомендована для газобетона под гипсовую штукатурку. Уточните у специалиста отдела.', unverified: true },
          { id: 'dt7', at: 168, speaker: 'employee', text: 'Секунду, позову специалиста.', momentId: 'dm3' },
          { id: 'dt8', at: 292, speaker: 'colleague', text: 'На газобетон — только глубокого проникновения, в два слоя. Иначе штукатурка отойдёт через сезон.' },
          { id: 'dt9', at: 344, speaker: 'client', text: 'Понял. Я пока прикину объём и вернусь.' },
          { id: 'dt10', at: 356, speaker: 'employee', text: 'Хорошо, ждём.', momentId: 'dm4' },
          { id: 'dt11', at: 366, speaker: 'ai', text: 'Подсказка: предложите расчёт. Расход грунта 150 мл/м² в два слоя — посчитайте вместе с клиентом и добавьте штукатурку в чек.' },
        ],
        summary:
          'Сделка потеряна на подборе. Основание не уточнено, поэтому рекомендация оказалась ошибочной — Onvy остановил ответ и потребовал подтверждения. Расчёт объёма не сделан, клиент ушёл считать самостоятельно.',
        recommendations: [
          'Первый вопрос при подборе — основание и условия работ. Без него любая рекомендация угадывание.',
          'Совместимость грунтовок есть в базе знаний: ответ занимает 10 секунд вместо двух минут ожидания специалиста.',
          'Считайте объём при клиенте. Расчёт удерживает клиента и добавляет сопутствующие материалы в чек.',
        ],
      },
      {
        id: 'dd2',
        employeeId: 'q1',
        pointId: 'm1',
        startedAt: '2026-07-29T14:15:00',
        durationSec: 604,
        outcome: 'success',
        revenue: 42_800,
        scriptScore: 96,
        responseSec: 2.9,
        category: 'Подбор материала',
        topic: 'Штукатурка комнаты под ключ',
        items: [
          { name: 'Штукатурка гипсовая, 30 кг', qty: 14, price: 29_400 },
          { name: 'Грунтовка глубокого проникновения, 10 л', qty: 2, price: 4_800 },
          { name: 'Профиль маячковый', qty: 12, price: 3_600 },
          { name: 'Правило, 2 м', qty: 1, price: 2_200 },
          { name: 'Сетка армирующая', qty: 2, price: 2_800 },
        ],
        helpRequests: 0,
        hasCue: true,
        wave: makeWave(802),
        moments: [
          { id: 'dm5', at: 10, type: 'win', title: 'Уточнил основание и условия', note: 'Газобетон, неотапливаемое помещение зимой — оба фактора влияют на выбор смеси.' },
          { id: 'dm6', at: 34, type: 'win', title: 'Посчитал расход при клиенте', note: '18 м² при слое 10 мм — 14 мешков. Клиент увидел цифру и не пошёл сравнивать.' },
          { id: 'dm7', at: 58, type: 'win', title: 'Предупредил о технологии', note: 'Грунт в два слоя с межслойной сушкой — снимает будущую рекламацию.' },
          { id: 'dm8', at: 84, type: 'win', title: 'Собрал сопутствующие материалы', note: 'Маяки, правило, сетка. Чек вырос с 29 400 до 42 800 ₽.' },
        ],
        transcript: [
          { id: 'dt20', at: 8, speaker: 'client', text: 'Нужна штукатурка на комнату. Что взять?' },
          { id: 'dt21', at: 16, speaker: 'employee', text: 'Давайте по порядку: какое основание — кирпич, газобетон, бетон? И помещение отапливается зимой?', momentId: 'dm5' },
          { id: 'dt22', at: 32, speaker: 'client', text: 'Газобетон. Зимой пока не отапливается, ремонт идёт.' },
          { id: 'dt23', at: 44, speaker: 'ai', text: 'Подсказка: газобетон плюс неотапливаемое помещение — гипсовая смесь подойдёт только при завершении работ до холодов. Уточните сроки.' },
          { id: 'dt24', at: 58, speaker: 'employee', text: 'Тогда важный момент: гипсовую штукатурку кладём, если закончите до холодов. Если позже — берём цементную. Когда планируете?' },
          { id: 'dt25', at: 96, speaker: 'client', text: 'До сентября точно закончу.' },
          { id: 'dt26', at: 148, speaker: 'employee', text: 'Отлично. Площадь комнаты какая? Посчитаем точно, чтобы не ездить второй раз.', momentId: 'dm6' },
          { id: 'dt27', at: 176, speaker: 'client', text: 'Восемнадцать квадратов примерно.' },
          { id: 'dt28', at: 196, speaker: 'employee', text: 'При слое 10 мм расход 8,5 кг на квадрат — это 153 кг, берём 14 мешков с запасом. Грунтовки нужно 10 литров на два слоя, возьмём две канистры.' },
          { id: 'dt29', at: 328, speaker: 'employee', text: 'И важно: грунт наносим в два слоя, второй — после полного высыхания первого. Иначе штукатурка отойдёт.', momentId: 'dm7' },
          { id: 'dt30', at: 452, speaker: 'employee', text: 'Маяки нужны — без них слой не выведете. Правило есть? И сетку на углы возьмите, чтобы не потрескалось.', momentId: 'dm8' },
          { id: 'dt31', at: 486, speaker: 'client', text: 'Правила нет, давайте. И сетку тоже.' },
        ],
        summary:
          'Эталонный подбор: основание и условия уточнены до рекомендации, расход посчитан при клиенте, технология проговорена, сопутствующие материалы собраны логикой работ. Чек вырос на 46 % относительно исходного запроса.',
        recommendations: [
          'Связка «основание — сроки — расчёт — технология — сопутствующие» даёт лучший результат в сети. Стоит разобрать её на планёрке.',
          'Предупреждение о межслойной сушке снимает рекламации. Продолжайте проговаривать это всегда.',
        ],
      },
      {
        id: 'dd3',
        employeeId: 'q5',
        pointId: 'm2',
        startedAt: '2026-07-28T16:50:00',
        durationSec: 352,
        outcome: 'success',
        revenue: 18_600,
        scriptScore: 64,
        responseSec: 8.1,
        category: 'Наличие и доставка',
        topic: 'Гидроизоляция санузла',
        items: [
          { name: 'Гидроизоляция обмазочная', qty: 2, price: 8_000 },
          { name: 'Смесь для стяжки', qty: 6, price: 10_600 },
        ],
        helpRequests: 3,
        hasCue: true,
        wave: makeWave(803),
        moments: [
          { id: 'dm9', at: 16, type: 'miss', title: 'Не уточнил тип помещения', note: 'Санузел или душевая — от этого зависит зона обработки и объём.' },
          { id: 'dm10', at: 38, type: 'help', title: 'Обращение к складу по наличию', note: 'Остатки есть в базе Onvy. Уточнение заняло 90 секунд.' },
          { id: 'dm11', at: 66, type: 'help', title: 'Повторное обращение по срокам поставки', note: 'Второе обращение по тому же товару.' },
          { id: 'dm12', at: 88, type: 'miss', title: 'Не предложил ленту для примыканий', note: 'Без ленты гидроизоляция в углах не работает. Клиент вернётся за ней отдельно.' },
        ],
        transcript: [
          { id: 'dt40', at: 14, speaker: 'client', text: 'Нужна гидроизоляция под плитку в ванной.' },
          { id: 'dt41', at: 22, speaker: 'employee', text: 'Вот обмазочная, две банки хватит.', momentId: 'dm9' },
          { id: 'dt42', at: 30, speaker: 'ai', text: 'Подсказка: уточните, это санузел целиком или зона душа. От этого зависит площадь обработки и нужна ли лента для примыканий.' },
          { id: 'dt43', at: 82, speaker: 'employee', text: 'Секунду, уточню на складе, сколько осталось.', momentId: 'dm10' },
          { id: 'dt44', at: 96, speaker: 'ai', text: 'Подсказка: остаток на точке — 14 банок, данные из базы. Обращение к складу не требуется.' },
          { id: 'dt45', at: 214, speaker: 'employee', text: 'Ещё уточню, когда следующая поставка, на всякий случай.', momentId: 'dm11' },
          { id: 'dt46', at: 302, speaker: 'ai', text: 'Подсказка: к обмазочной гидроизоляции обязательна лента для примыканий — без неё углы протекут.' },
          { id: 'dt47', at: 318, speaker: 'employee', text: 'Всё, пробивайте на кассе.', momentId: 'dm12' },
        ],
        summary:
          'Сделка состоялась, но с потерями. Тип помещения не уточнён, три обращения за информацией, которая есть в базе, и не предложена лента для примыканий — клиент вернётся за ней отдельно.',
        recommendations: [
          'Остатки и сроки поставки есть в базе Onvy — обращение к складу удлиняет консультацию втрое.',
          'Лента для примыканий идёт с обмазочной гидроизоляцией всегда. Это не допродажа, а часть технологии.',
        ],
      },
    ],
    tests: [
      {
        id: 'dts1',
        title: 'Совместимость грунтовок и оснований',
        description: 'Собран по 96 ошибкам в рекомендациях за месяц.',
        source: 'errors',
        sourceDetail: 'Ошибки консультантов · Совместимость',
        createdAt: '2026-07-27',
        createdBy: 'Виктор Пахомов',
        deadline: '2026-08-06',
        passScore: 80,
        questions: [
          {
            id: 'dq1',
            question: 'Клиент штукатурит газобетон гипсовой смесью. Какую грунтовку рекомендовать?',
            options: [
              'Универсальную — подходит под любое основание',
              'Глубокого проникновения, в два слоя',
              'Бетоноконтакт',
              'Грунтовка не нужна, газобетон и так пористый',
            ],
            correct: 1,
            explain: 'Газобетон сильно впитывает влагу. Без грунта глубокого проникновения гипсовая штукатурка отойдёт через сезон — это прямая рекламация.',
            source: 'Совместимость',
          },
          {
            id: 'dq2',
            question: 'С чего начинается подбор материала?',
            options: [
              'С показа популярной позиции',
              'С уточнения основания и условий работ',
              'С вопроса о бюджете',
              'С расчёта площади',
            ],
            correct: 1,
            explain: 'Основание и условия определяют, какой материал вообще применим. Всё остальное считается после.',
            source: 'Скрипты продаж',
          },
          {
            id: 'dq3',
            question: 'Onvy показал «Информация не подтверждена». Ваши действия?',
            options: [
              'Ответить по опыту',
              'Уточнить у специалиста отдела и только потом рекомендовать',
              'Предложить другой товар',
              'Сказать клиенту, что не знаете',
            ],
            correct: 1,
            explain: 'Onvy не придумывает ответ, если данных нет. Ошибка в подборе возвращается рекламацией и потерей клиента.',
            source: 'Техника безопасности',
          },
        ],
        assignedTo: ['q3', 'q5', 'q7'],
        results: { q5: 67 },
      },
      {
        id: 'dts2',
        title: 'Расчёт расхода материалов',
        description: 'Собран по частым вопросам «сколько нужно на комнату».',
        source: 'questions',
        sourceDetail: 'Частые вопросы · Расход и объём',
        createdAt: '2026-07-22',
        createdBy: 'Виктор Пахомов',
        deadline: '2026-08-03',
        passScore: 70,
        questions: [
          {
            id: 'dq4',
            question: 'Комната 18 м², гипсовая штукатурка слоем 10 мм. Расход 8,5 кг/м². Сколько мешков по 30 кг?',
            options: ['9 мешков', '14 мешков с запасом', '6 мешков', '20 мешков'],
            correct: 1,
            explain: '18 × 8,5 = 153 кг, это 5,1 мешка на слой. С учётом неровностей и запаса берём 14 — на практике слой выходит толще расчётного.',
            source: 'Характеристики материалов',
          },
          {
            id: 'dq5',
            question: 'Зачем считать расход при клиенте?',
            options: [
              'Так требует регламент',
              'Клиент видит цифру, не идёт сравнивать и берёт сопутствующие материалы сразу',
              'Чтобы занять время',
              'Чтобы продать больше, чем нужно',
            ],
            correct: 1,
            explain: 'Расчёт удерживает клиента и естественно добавляет в чек маяки, правило и сетку. Завышать объём нельзя — это возвраты.',
            source: 'Скрипты продаж',
          },
        ],
        assignedTo: ['q3', 'q5', 'q7'],
        results: { q7: 100, q3: 50 },
      },
      {
        id: 'dts3',
        title: 'Техника безопасности и технология',
        description: 'Загружен из файла «ТБ и технологические карты.pdf».',
        source: 'file',
        sourceDetail: 'Файл · ТБ и технологические карты.pdf',
        createdAt: '2026-06-30',
        createdBy: 'Виктор Пахомов',
        deadline: '2026-07-31',
        passScore: 70,
        questions: [
          {
            id: 'dq6',
            question: 'Клиент берёт обмазочную гидроизоляцию для санузла. Что обязательно добавить?',
            options: ['Валик', 'Ленту для примыканий', 'Грунтовку', 'Шпатель'],
            correct: 1,
            explain: 'Без ленты углы и примыкания протекут. Это не допродажа, а обязательная часть технологии.',
            source: 'Способы применения',
          },
          {
            id: 'dq7',
            question: 'О чём предупредить при нанесении грунта в два слоя?',
            options: [
              'Ни о чём, всё очевидно',
              'Второй слой наносится только после полного высыхания первого',
              'Слои наносятся сразу друг за другом',
              'Достаточно одного слоя',
            ],
            correct: 1,
            explain: 'Межслойная сушка обязательна. Нарушение технологии — самая частая причина отслоения и рекламаций.',
            source: 'Способы применения',
          },
        ],
        assignedTo: ['q3', 'q5'],
        results: { q3: 50 },
      },
    ],
    faq: [
      {
        id: 'df1',
        question: 'Есть ли это на складе?',
        category: 'Наличие и доставка',
        count: 1_206,
        trend: 5,
        conversion: 46,
        avgResponseSec: 12.4,
        bestAnswer: 'Смотреть остатки в базе Onvy — данные обновляются каждый час. Звонить на склад не нужно.',
        weakSpot: '691 обращение к складу за месяц при том, что ответ есть в базе.',
        source: 'Складские остатки',
        updatedAt: '2026-07-29',
        status: 'published',
        verified: true,
      },
      {
        id: 'df2',
        question: 'Какую грунтовку взять под эту штукатурку?',
        category: 'Совместимость',
        count: 664,
        trend: 11,
        conversion: 42,
        avgResponseSec: 9.8,
        bestAnswer: 'Сначала уточнить основание. Газобетон и пористые основания — только глубокого проникновения, в два слоя.',
        weakSpot: 'Артур Бикмуллин, Павел Мещеряков — рекомендуют универсальную без вопроса об основании.',
        source: 'Совместимость',
        updatedAt: '2026-07-25',
        status: 'published',
        verified: true,
      },
      {
        id: 'df3',
        question: 'Это подойдёт для влажного помещения?',
        category: 'Совместимость',
        count: 606,
        trend: 14,
        conversion: 38,
        avgResponseSec: 10.6,
        bestAnswer: 'Проверить класс влагостойкости в карточке товара и назвать ограничения по зоне применения.',
        weakSpot: 'Самый частый источник ошибочных рекомендаций: 96 случаев за месяц.',
        source: 'Характеристики материалов',
        updatedAt: '2026-07-24',
        status: 'published',
        verified: true,
      },
      {
        id: 'df4',
        question: 'Сколько мешков нужно на комнату?',
        category: 'Расход и объём',
        count: 356,
        trend: -3,
        conversion: 68,
        avgResponseSec: 6.2,
        bestAnswer: 'Считать при клиенте: площадь × расход × слой, плюс запас. Сразу добавлять маяки, правило и сетку.',
        weakSpot: 'Работает хорошо у Сергея Демидова. Стажёры расчёт не делают вовсе.',
        source: 'Характеристики материалов',
        updatedAt: '2026-07-26',
        status: 'published',
        verified: true,
      },
      {
        id: 'df5',
        question: 'Чем обработать дерево на улице?',
        category: 'Подбор материала',
        count: 148,
        trend: 7,
        conversion: 66,
        avgResponseSec: 5.4,
        bestAnswer: 'Антисептик плюс атмосферостойкое покрытие. Обязательно предупредить о повторной обработке через сезон.',
        weakSpot: 'Только Тюмень отрабатывает этот вопрос стабильно.',
        source: 'Способы применения',
        updatedAt: '2026-07-19',
        status: 'published',
        verified: true,
      },
      {
        id: 'df6',
        question: 'Нужны ли средства защиты при работе с этим составом?',
        category: 'Безопасность',
        count: 96,
        trend: 2,
        conversion: 54,
        avgResponseSec: 7.1,
        bestAnswer: 'Проверить класс опасности в карте материала и назвать необходимые СИЗ.',
        weakSpot: 'Данные по части составов не обновлялись с апреля — требуется подтверждение поставщика.',
        source: 'Техника безопасности',
        updatedAt: '2026-04-18',
        status: 'outdated',
        verified: false,
      },
    ],
    scriptErrors: [
      { id: 'dse1', label: 'Не уточнено основание и условия работ', count: 284, costPerMonth: 1_640_000, employees: ['Артур Бикмуллин', 'Павел Мещеряков', 'Динара Хафизова'] },
      { id: 'dse2', label: 'Рекомендация несовместимых материалов', count: 96, costPerMonth: 2_180_000, employees: ['Павел Мещеряков', 'Артур Бикмуллин'] },
      { id: 'dse3', label: 'Не рассчитан расход', count: 342, costPerMonth: 1_240_000, employees: ['Артур Бикмуллин', 'Динара Хафизова', 'Павел Мещеряков'] },
      { id: 'dse4', label: 'Не предложены сопутствующие материалы', count: 418, costPerMonth: 986_000, employees: ['Павел Мещеряков', 'Артур Бикмуллин'] },
      { id: 'dse5', label: 'Не предупредил о технологии и ТБ', count: 164, costPerMonth: 540_000, employees: ['Артур Бикмуллин', 'Наталья Ковалёва'] },
    ],
    knowledgeFiles: [
      { id: 'dkf1', name: 'Каталог_материалов.xlsx', sizeKb: 2_140, uploadedAt: '2026-04-12', kind: 'materials', categories: ['Отделка', 'Крепёж', 'Сантехника', 'Сад'], records: 8_642 },
      { id: 'dkf2', name: 'Матрица_совместимости.xlsx', sizeKb: 486, uploadedAt: '2026-04-14', kind: 'compat', categories: ['Основания', 'Грунты', 'Штукатурки'], records: 1_284 },
      { id: 'dkf3', name: 'ТБ и технологические карты.pdf', sizeKb: 1_860, uploadedAt: '2026-04-14', kind: 'safety', categories: ['СИЗ', 'Классы опасности', 'Технология'], records: 342 },
      { id: 'dkf4', name: 'Остатки_склад.csv', sizeKb: 940, uploadedAt: '2026-07-29', kind: 'stock', categories: ['Наличие', 'Сроки поставки'], records: 8_642 },
    ],
    pilot: {
      startedAt: '2026-06-15',
      weeks: 6,
      scope: '3 гипермаркета · 7 консультантов',
      goals: [
        'Снизить ошибки в рекомендациях по совместимости материалов',
        'Убрать обращения к специалисту за данными, которые есть в базе',
        'Сделать расчёт расхода обязательным этапом подбора',
        'Ускорить выход новичка на самостоятельную работу',
      ],
      metrics: [
        { key: 'responseSec', label: 'Скорость ответа', before: 11.8, during: 6.3, unit: 'sec', better: 'down' },
        { key: 'autonomy', label: 'Решено самостоятельно', before: 54, during: 76, unit: 'pct', better: 'up' },
        { key: 'specialistEscalations', label: 'Обращения к специалисту и складу', before: 1_486, during: 891, unit: 'count', better: 'down' },
        { key: 'scriptCompliance', label: 'Выполнение скрипта подбора', before: 61, during: 79, unit: 'pct', better: 'up' },
        { key: 'wrongAdvice', label: 'Ошибки в рекомендациях', before: 214, during: 131, unit: 'count', better: 'down' },
        { key: 'training', label: 'Прогресс обучения', before: 31, during: 76, unit: 'pct', better: 'up' },
        { key: 'badgeCoverage', label: 'Покрытие бейджами', before: 0, during: 71, unit: 'pct', better: 'up' },
        { key: 'companionSales', label: 'Сопутствующие материалы', before: 28, during: 39, unit: 'pct', better: 'up' },
        { key: 'avgCheck', label: 'Средний чек', before: 7_240, during: 7_980, unit: 'money', better: 'up', external: true },
      ],
    },
    adaptation: {
      daysToSolo: 18,
      daysToSoloBefore: 45,
      requiredModules: 3,
      completion: 76,
      firstCheckScore: 54,
      repeatedErrors: 26,
      noviceHelpPerShift: 7.4,
      earlyCompliance: 64,
    },
    bestPractices: [
      {
        id: 'dbp1',
        employeeId: 'q1',
        pointId: 'm1',
        title: 'Основание и сроки до подбора материала',
        quote: 'Какое основание — кирпич, газобетон, бетон? И помещение отапливается зимой?',
        effect: 'Три ошибки в рекомендациях за месяц при среднем по сети 44.',
        category: 'Совместимость',
        dialogId: 'dd2',
        inTraining: true,
      },
      {
        id: 'dbp2',
        employeeId: 'q1',
        pointId: 'm1',
        title: 'Расчёт расхода при клиенте',
        quote: 'При слое 10 мм расход 8,5 кг на квадрат — это 153 кг, берём 14 мешков с запасом.',
        effect: 'Клиент не идёт сравнивать, сопутствующие материалы уходят в 61 % чеков.',
        category: 'Расход и объём',
        dialogId: 'dd2',
        inTraining: true,
      },
      {
        id: 'dbp3',
        employeeId: 'q6',
        pointId: 'm3',
        title: 'Предупреждение о технологии',
        quote: 'Грунт наносим в два слоя, второй — после полного высыхания первого.',
        effect: 'Точность подбора 93 %, рекламаций по отслоению нет.',
        category: 'Безопасность',
        inTraining: false,
      },
    ],
    trainingOutcomes: [
      {
        testId: 'dts1',
        reason: '96 ошибочных рекомендаций по совместимости за месяц',
        origin: 'Разбор консультаций · категория «Совместимость»',
        metric: 'wrongAdvice',
        metricLabel: 'Ошибки в рекомендациях',
        before: 96,
        after: 58,
        unit: 'count',
        better: 'down',
        repeated: true,
      },
      {
        testId: 'dts2',
        reason: 'Расчёт расхода не делался — клиенты возвращались за добавкой',
        origin: 'Частые вопросы · «Сколько нужно на комнату»',
        metric: 'companionSales',
        metricLabel: 'Сопутствующие материалы',
        before: 28,
        after: 39,
        unit: 'pct',
        better: 'up',
        repeated: false,
      },
      {
        testId: 'dts3',
        reason: '164 случая без предупреждения о технологии и ТБ',
        origin: 'ТБ и технологические карты · загруженный документ',
        metric: 'scriptCompliance',
        metricLabel: 'Выполнение скрипта подбора',
        before: 61,
        after: 79,
        unit: 'pct',
        better: 'up',
        repeated: false,
      },
    ],
  };
}
