import type { AppData } from '../types';
import { daily, makeWave } from './shared';

/** Демо-пространство «Электроника» — сеть «Стартех». */
export function electronicsSpace(): AppData {
  return {
    space: 'electronics',
    company: {
      id: 'c1',
      name: 'Стартех',
      industry: 'electronics',
      staffSize: '50–200',
      pointsPlanned: '4',
      city: 'Москва',
      joinCode: 'STARTECH-2026',
      createdAt: '2026-01-15',
    },
    points: [
      {
        id: 'p1',
        name: 'Стартех Авиапарк',
        city: 'Москва',
        address: 'Ходынский бул., 4',
        zones: ['Смартфоны', 'Ноутбуки', 'Аксессуары'],
        manager: 'Артём Кузнецов',
        staffCount: 3,
        badgesOnline: 3,
        plan: 9_800_000,
        revenue: 10_412_000,
        avgCheck: 42_300,
        interactions: 1284,
        conversion: 24.1,
        scriptCompliance: 88,
        training: 86,
        helpRequests: 142,
        industry: {
          itemsPerCheck: 2.4,
          upsellRate: 41,
          warrantyOffer: 34,
          accessoryOffer: 58,
          stockQueries: 214,
          stockEscalations: 62,
          missedStages: 96,
        },
      },
      {
        id: 'p2',
        name: 'Стартех Метрополис',
        city: 'Москва',
        address: 'Ленинградское ш., 16а',
        zones: ['Смартфоны', 'ТВ и аудио'],
        manager: 'Ольга Панина',
        staffCount: 2,
        badgesOnline: 2,
        plan: 8_200_000,
        revenue: 7_640_000,
        avgCheck: 38_900,
        interactions: 1102,
        conversion: 19.4,
        scriptCompliance: 84,
        training: 78,
        helpRequests: 168,
        industry: {
          itemsPerCheck: 2.1,
          upsellRate: 34,
          warrantyOffer: 27,
          accessoryOffer: 46,
          stockQueries: 186,
          stockEscalations: 81,
          missedStages: 134,
        },
      },
      {
        id: 'p3',
        name: 'Стартех Галерея',
        city: 'Санкт-Петербург',
        address: 'Лиговский пр., 30а',
        zones: ['Смартфоны', 'Умный дом'],
        manager: 'Елена Бортник',
        staffCount: 2,
        badgesOnline: 1,
        plan: 6_500_000,
        revenue: 6_915_000,
        avgCheck: 40_100,
        interactions: 968,
        conversion: 22.8,
        scriptCompliance: 84,
        training: 87,
        helpRequests: 119,
        industry: {
          itemsPerCheck: 2.3,
          upsellRate: 38,
          warrantyOffer: 31,
          accessoryOffer: 52,
          stockQueries: 148,
          stockEscalations: 54,
          missedStages: 108,
        },
      },
      {
        id: 'p4',
        name: 'Стартех Мега Казань',
        city: 'Казань',
        address: 'пр. Победы, 141',
        zones: ['Смартфоны', 'Ноутбуки'],
        manager: 'Рустам Хайруллин',
        staffCount: 1,
        badgesOnline: 0,
        plan: 5_400_000,
        revenue: 4_180_000,
        avgCheck: 33_600,
        interactions: 742,
        conversion: 15.2,
        scriptCompliance: 74,
        training: 92,
        helpRequests: 96,
        industry: {
          itemsPerCheck: 1.7,
          upsellRate: 22,
          warrantyOffer: 14,
          accessoryOffer: 29,
          stockQueries: 121,
          stockEscalations: 44,
          missedStages: 167,
        },
      },
    ],
    accounts: [
      {
        id: 'a1',
        role: 'rop',
        name: 'Анастасия Наумкина',
        email: 'rop@startech.ru',
        password: 'onvy2026',
        companyId: 'c1',
        position: 'Руководитель отдела продаж',
        focus: 'sales',
      },
      {
        id: 'a2',
        role: 'employee',
        name: 'Артём Кузнецов',
        email: 'artem@startech.ru',
        password: 'onvy2026',
        companyId: 'c1',
        pointId: 'p1',
        position: 'Старший консультант',
        employeeId: 'e1',
      },
    ],
    employees: [
      {
        id: 'e1',
        name: 'Артём Кузнецов',
        position: 'Старший консультант',
        pointId: 'p1',
        hiredAt: '2024-03-11',
        onboarding: 100,
        level: 7,
        xp: 6420,
        badgeOnline: true,
        badgeBattery: 82,
        micQuality: 94,
        stats: {
          revenue: 4_120_000,
          deals: 97,
          dialogs: 402,
          avgCheck: 42_474,
          conversion: 24.1,
          scriptCompliance: 92,
          responseSec: 3.1,
          autonomy: 91,
          helpRequests: 36,
        },
        industry: {
          itemsPerCheck: 2.6,
          upsellRate: 46,
          warrantyOffer: 28,
          accessoryOffer: 64,
          stockQueries: 74,
          stockEscalations: 18,
          missedStages: 21,
        },
        daily: daily(11, 290_000),
        topItems: [
          { name: 'iPhone 15 Pro', qty: 24, revenue: 2_640_000 },
          { name: 'MacBook Air M3', qty: 11, revenue: 1_089_000 },
          { name: 'AirPods Pro 2', qty: 31, revenue: 744_000 },
          { name: 'Защитное стекло', qty: 58, revenue: 87_000 },
        ],
        topRequests: [
          { label: 'Чем Pro отличается от обычной модели?', count: 88, conversion: 31 },
          { label: 'Есть ли рассрочка без переплаты?', count: 64, conversion: 27 },
          { label: 'Сколько держит батарея?', count: 51, conversion: 22 },
          { label: 'Что с гарантией на технику?', count: 34, conversion: 19 },
        ],
        strengths: [
          'Всегда выявляет потребность до показа товара',
          'Уверенно отрабатывает возражение «дорого» через сравнение стоимости владения',
          'Высокий процент допродаж аксессуаров — 46 %',
        ],
        growthAreas: [
          'Редко предлагает расширенную гарантию — упущено ≈ 180 000 ₽ за месяц',
          'В 3 из 10 консультаций не назначает следующий шаг, если клиент уходит подумать',
        ],
        trainingDone: 3,
        trainingTotal: 3,
      },
      {
        id: 'e2',
        name: 'Мария Соколова',
        position: 'Консультант',
        pointId: 'p1',
        hiredAt: '2025-09-02',
        onboarding: 100,
        level: 5,
        xp: 4180,
        badgeOnline: true,
        badgeBattery: 64,
        micQuality: 88,
        stats: {
          revenue: 3_480_000,
          deals: 84,
          dialogs: 388,
          avgCheck: 41_428,
          conversion: 21.6,
          scriptCompliance: 88,
          responseSec: 3.6,
          autonomy: 86,
          helpRequests: 48,
        },
        industry: {
          itemsPerCheck: 2.2,
          upsellRate: 39,
          warrantyOffer: 31,
          accessoryOffer: 51,
          stockQueries: 68,
          stockEscalations: 22,
          missedStages: 32,
        },
        daily: daily(22, 248_000),
        topItems: [
          { name: 'iPhone 15', qty: 29, revenue: 2_320_000 },
          { name: 'Apple Watch S9', qty: 14, revenue: 588_000 },
          { name: 'Чехлы и кейсы', qty: 72, revenue: 216_000 },
        ],
        topRequests: [
          { label: 'Чем Pro отличается от обычной модели?', count: 71, conversion: 29 },
          { label: 'Можно ли обменять старый телефон?', count: 58, conversion: 34 },
          { label: 'Есть ли рассрочка без переплаты?', count: 44, conversion: 25 },
        ],
        strengths: [
          'Тёплый контакт: клиенты чаще возвращаются именно к ней',
          'Хорошо работает с trade-in — результативность 34 %',
        ],
        growthAreas: [
          'Путается в характеристиках ноутбуков — 12 запросов ушли к коллеге',
          'Средняя пауза перед ответом 3,6 сек против 3,1 по точке',
        ],
        trainingDone: 2,
        trainingTotal: 3,
      },
      {
        id: 'e3',
        name: 'Данил Ефремов',
        position: 'Стажёр',
        pointId: 'p1',
        hiredAt: '2026-07-06',
        onboarding: 58,
        level: 2,
        xp: 980,
        badgeOnline: true,
        badgeBattery: 91,
        micQuality: 76,
        stats: {
          revenue: 1_180_000,
          deals: 31,
          dialogs: 244,
          avgCheck: 38_064,
          conversion: 12.7,
          scriptCompliance: 71,
          responseSec: 6.8,
          autonomy: 58,
          helpRequests: 102,
        },
        industry: {
          itemsPerCheck: 1.4,
          upsellRate: 14,
          warrantyOffer: 6,
          accessoryOffer: 18,
          stockQueries: 44,
          stockEscalations: 38,
          missedStages: 88,
        },
        daily: daily(33, 84_000),
        topItems: [
          { name: 'iPhone 15', qty: 12, revenue: 960_000 },
          { name: 'Аксессуары', qty: 24, revenue: 72_000 },
        ],
        topRequests: [
          { label: 'Сколько держит батарея?', count: 47, conversion: 11 },
          { label: 'Чем Pro отличается от обычной модели?', count: 39, conversion: 9 },
          { label: 'Есть ли рассрочка без переплаты?', count: 28, conversion: 14 },
        ],
        strengths: ['Не боится подходить к клиенту первым', 'Быстро принял стандарт приветствия'],
        growthAreas: [
          'Не знает отличий линейки Pro — 39 запросов с результативностью 9 %',
          'Пропускает этап выявления потребности в 6 консультациях из 10',
          'Не предлагает аксессуары: допродажи 14 % против 46 % у лидера',
        ],
        trainingDone: 0,
        trainingTotal: 3,
      },
      {
        id: 'e4',
        name: 'Ольга Панина',
        position: 'Старший консультант',
        pointId: 'p2',
        hiredAt: '2024-11-20',
        onboarding: 100,
        level: 6,
        xp: 5310,
        badgeOnline: true,
        badgeBattery: 47,
        micQuality: 91,
        stats: {
          revenue: 4_390_000,
          deals: 108,
          dialogs: 561,
          avgCheck: 40_648,
          conversion: 19.3,
          scriptCompliance: 90,
          responseSec: 3.4,
          autonomy: 89,
          helpRequests: 54,
        },
        industry: {
          itemsPerCheck: 2.7,
          upsellRate: 41,
          warrantyOffer: 24,
          accessoryOffer: 56,
          stockQueries: 91,
          stockEscalations: 26,
          missedStages: 38,
        },
        daily: daily(44, 313_000),
        topItems: [
          { name: 'Телевизор LG OLED', qty: 18, revenue: 2_160_000 },
          { name: 'Саундбар Samsung', qty: 22, revenue: 946_000 },
          { name: 'iPhone 15', qty: 16, revenue: 1_280_000 },
        ],
        topRequests: [
          { label: 'Какой телевизор взять в маленькую комнату?', count: 66, conversion: 33 },
          { label: 'Нужен ли саундбар к этому ТВ?', count: 52, conversion: 44 },
          { label: 'Есть ли доставка и установка?', count: 41, conversion: 28 },
        ],
        strengths: ['Лучший комплексный чек на сети: ТВ + саундбар', 'Держит скрипт на 90 %'],
        growthAreas: ['Долгие консультации — 14 мин при норме 9', 'Мало работает с рассрочкой'],
        trainingDone: 3,
        trainingTotal: 3,
      },
      {
        id: 'e5',
        name: 'Тимур Валиев',
        position: 'Консультант',
        pointId: 'p2',
        hiredAt: '2025-04-18',
        onboarding: 100,
        level: 4,
        xp: 3240,
        badgeOnline: true,
        badgeBattery: 73,
        micQuality: 83,
        stats: {
          revenue: 3_250_000,
          deals: 79,
          dialogs: 541,
          avgCheck: 41_139,
          conversion: 14.6,
          scriptCompliance: 79,
          responseSec: 4.9,
          autonomy: 72,
          helpRequests: 88,
        },
        industry: {
          itemsPerCheck: 1.8,
          upsellRate: 28,
          warrantyOffer: 12,
          accessoryOffer: 34,
          stockQueries: 62,
          stockEscalations: 34,
          missedStages: 74,
        },
        daily: daily(55, 232_000),
        topItems: [
          { name: 'iPhone 15 Pro Max', qty: 15, revenue: 2_100_000 },
          { name: 'Наушники Sony', qty: 26, revenue: 624_000 },
        ],
        topRequests: [
          { label: 'Есть ли рассрочка без переплаты?', count: 74, conversion: 18 },
          { label: 'Когда будет скидка?', count: 49, conversion: 8 },
          { label: 'Чем Pro отличается от обычной модели?', count: 37, conversion: 21 },
        ],
        strengths: ['Хорошо знает ассортимент аудио'],
        growthAreas: [
          'Соглашается ждать скидку вместо работы с ценностью — 49 запросов, результативность 8 %',
          'Скрипт выполнен на 79 % — ниже нормы точки',
        ],
        trainingDone: 1,
        trainingTotal: 3,
      },
      {
        id: 'e6',
        name: 'Елена Бортник',
        position: 'Консультант',
        pointId: 'p3',
        hiredAt: '2025-02-03',
        onboarding: 100,
        level: 6,
        xp: 4870,
        badgeOnline: true,
        badgeBattery: 55,
        micQuality: 92,
        stats: {
          revenue: 3_980_000,
          deals: 95,
          dialogs: 421,
          avgCheck: 41_894,
          conversion: 22.6,
          scriptCompliance: 91,
          responseSec: 3.2,
          autonomy: 90,
          helpRequests: 41,
        },
        industry: {
          itemsPerCheck: 2.8,
          upsellRate: 44,
          warrantyOffer: 26,
          accessoryOffer: 61,
          stockQueries: 58,
          stockEscalations: 19,
          missedStages: 27,
        },
        daily: daily(66, 284_000),
        topItems: [
          { name: 'Робот-пылесос Dreame', qty: 27, revenue: 1_053_000 },
          { name: 'iPhone 15', qty: 19, revenue: 1_520_000 },
          { name: 'Умные лампы', qty: 63, revenue: 189_000 },
        ],
        topRequests: [
          { label: 'С чего начать умный дом?', count: 58, conversion: 41 },
          { label: 'Работает ли это без интернета?', count: 44, conversion: 26 },
          { label: 'Есть ли рассрочка без переплаты?', count: 31, conversion: 23 },
        ],
        strengths: ['Продаёт сценарием «умный дом», а не отдельными коробками', 'Допродажи 44 %'],
        growthAreas: ['Иногда перегружает клиента деталями — 4 консультации дольше 15 мин'],
        trainingDone: 3,
        trainingTotal: 3,
      },
      {
        id: 'e7',
        name: 'Никита Ларин',
        position: 'Стажёр',
        pointId: 'p3',
        hiredAt: '2026-06-22',
        onboarding: 74,
        level: 3,
        xp: 1640,
        badgeOnline: false,
        badgeBattery: 12,
        micQuality: 71,
        stats: {
          revenue: 1_640_000,
          deals: 44,
          dialogs: 298,
          avgCheck: 37_272,
          conversion: 14.8,
          scriptCompliance: 76,
          responseSec: 5.7,
          autonomy: 64,
          helpRequests: 94,
        },
        industry: {
          itemsPerCheck: 1.5,
          upsellRate: 19,
          warrantyOffer: 9,
          accessoryOffer: 24,
          stockQueries: 48,
          stockEscalations: 31,
          missedStages: 62,
        },
        daily: daily(77, 117_000),
        topItems: [
          { name: 'iPhone 15', qty: 14, revenue: 1_120_000 },
          { name: 'Умные лампы', qty: 28, revenue: 84_000 },
        ],
        topRequests: [
          { label: 'Работает ли это без интернета?', count: 41, conversion: 12 },
          { label: 'С чего начать умный дом?', count: 33, conversion: 15 },
        ],
        strengths: ['Быстро растёт: +6 п.п. результативности за две недели'],
        growthAreas: [
          'Не знает совместимость протоколов умного дома',
          'Забывает про допродажу к базовым сценариям',
        ],
        trainingDone: 1,
        trainingTotal: 3,
      },
      {
        id: 'e8',
        name: 'Рустам Хайруллин',
        position: 'Консультант',
        pointId: 'p4',
        hiredAt: '2025-08-14',
        onboarding: 92,
        level: 4,
        xp: 2980,
        badgeOnline: false,
        badgeBattery: 0,
        micQuality: 68,
        stats: {
          revenue: 4_180_000,
          deals: 124,
          dialogs: 742,
          avgCheck: 33_709,
          conversion: 15.2,
          scriptCompliance: 74,
          responseSec: 5.2,
          autonomy: 69,
          helpRequests: 96,
        },
        industry: {
          itemsPerCheck: 1.7,
          upsellRate: 22,
          warrantyOffer: 14,
          accessoryOffer: 29,
          stockQueries: 121,
          stockEscalations: 44,
          missedStages: 167,
        },
        daily: daily(88, 298_000),
        topItems: [
          { name: 'Xiaomi Redmi Note', qty: 61, revenue: 1_403_000 },
          { name: 'Ноутбук Lenovo', qty: 19, revenue: 1_235_000 },
        ],
        topRequests: [
          { label: 'Что подешевле, но нормальное?', count: 96, conversion: 21 },
          { label: 'Есть ли рассрочка без переплаты?', count: 62, conversion: 19 },
          { label: 'Когда будет скидка?', count: 38, conversion: 7 },
        ],
        strengths: ['Огромный поток консультаций — 742 за месяц', 'Не теряет темп в час пик'],
        growthAreas: [
          'Сразу уводит клиента в нижний ценовой сегмент — средний чек ниже сети на 19 %',
          'Скрипт 74 %: пропускает презентацию выгод',
        ],
        trainingDone: 1,
        trainingTotal: 3,
      },
    ],
    kpis: [
      { id: 'k1', employeeId: 'e1', metric: 'revenue', target: 4_500_000, current: 4_120_000, period: 'month', setBy: 'Анастасия Наумкина' },
      { id: 'k2', employeeId: 'e1', metric: 'deals', target: 5, current: 3, period: 'day', setBy: 'Анастасия Наумкина', note: 'Фокус на iPhone 15 — приоритет месяца' },
      { id: 'k3', employeeId: 'e1', metric: 'warrantyOffer', target: 40, current: 28, period: 'week', setBy: 'Анастасия Наумкина', note: 'Гарантия — самая недоиспользованная допродажа' },
      { id: 'k4', employeeId: 'e2', metric: 'revenue', target: 3_800_000, current: 3_480_000, period: 'month', setBy: 'Анастасия Наумкина' },
      { id: 'k5', employeeId: 'e2', metric: 'avgCheck', target: 45_000, current: 41_428, period: 'week', setBy: 'Анастасия Наумкина' },
      { id: 'k6', employeeId: 'e3', metric: 'deals', target: 3, current: 1, period: 'day', setBy: 'Анастасия Наумкина', note: 'Стажёрский план — не занижаем, но помогаем' },
      { id: 'k7', employeeId: 'e3', metric: 'scriptCompliance', target: 85, current: 71, period: 'week', setBy: 'Анастасия Наумкина' },
      { id: 'k8', employeeId: 'e3', metric: 'autonomy', target: 75, current: 58, period: 'week', setBy: 'Анастасия Наумкина', note: 'Меньше дёргать коллег — искать ответ в базе' },
      { id: 'k9', employeeId: 'e4', metric: 'revenue', target: 4_200_000, current: 4_390_000, period: 'month', setBy: 'Анастасия Наумкина' },
      { id: 'k10', employeeId: 'e5', metric: 'conversion', target: 18, current: 14.6, period: 'week', setBy: 'Анастасия Наумкина' },
      { id: 'k11', employeeId: 'e6', metric: 'revenue', target: 3_700_000, current: 3_980_000, period: 'month', setBy: 'Анастасия Наумкина' },
      { id: 'k12', employeeId: 'e7', metric: 'scriptCompliance', target: 85, current: 76, period: 'week', setBy: 'Анастасия Наумкина' },
      { id: 'k13', employeeId: 'e8', metric: 'avgCheck', target: 40_000, current: 33_709, period: 'week', setBy: 'Анастасия Наумкина', note: 'Не уводить клиента вниз по цене сразу' },
    ],
    dialogs: [
      {
        id: 'd1',
        employeeId: 'e1',
        pointId: 'p1',
        startedAt: '2026-07-29T11:24:00',
        durationSec: 512,
        outcome: 'success',
        revenue: 134_000,
        scriptScore: 94,
        responseSec: 2.8,
        category: 'Выбор техники',
        topic: 'Выбор смартфона',
        items: [
          { name: 'iPhone 15 Pro 256 ГБ', qty: 1, price: 110_000 },
          { name: 'AirPods Pro 2', qty: 1, price: 24_000 },
        ],
        helpRequests: 0,
        hasCue: true,
        wave: makeWave(101),
        moments: [
          { id: 'm1', at: 12, type: 'win', title: 'Выявил потребность до показа', note: 'Спросил, как клиент пользуется камерой, и только потом повёл к витрине. Это подняло шанс на Pro-модель.' },
          { id: 'm2', at: 38, type: 'win', title: 'Сравнил стоимость владения', note: 'Перевёл разговор с цены на срок службы и остаточную стоимость — возражение «дорого» снялось за 40 секунд.' },
          { id: 'm3', at: 66, type: 'miss', title: 'Не предложил расширенную гарантию', note: 'Клиент сам спросил про «а если разобью». Идеальный момент для гарантии — упущено 12 000 ₽.' },
          { id: 'm4', at: 84, type: 'win', title: 'Допродал наушники в момент решения', note: 'Предложил AirPods, когда клиент уже согласился на телефон. Чек вырос на 24 000 ₽.' },
        ],
        transcript: [
          { id: 't1', at: 8, speaker: 'client', text: 'Здравствуйте, хочу посмотреть новый айфон. Не решил ещё, обычный или Pro.' },
          { id: 't2', at: 22, speaker: 'employee', text: 'Добрый день! Давайте я задам пару вопросов, чтобы не гадать. Вы много снимаете — фото, видео?', momentId: 'm1' },
          { id: 't3', at: 34, speaker: 'client', text: 'Да, детей постоянно снимаю. И в отпуске много видео.' },
          { id: 't4', at: 46, speaker: 'ai', text: 'Подсказка: у Pro — 5x телефото и запись в ProRes. Для съёмки детей в движении ключевое: быстрый автофокус и стабилизация.' },
          { id: 't5', at: 58, speaker: 'employee', text: 'Тогда смотрим Pro: у него пятикратный зум и лучше стабилизация — ребёнок в движении не смажется.' },
          { id: 't6', at: 96, speaker: 'client', text: 'Разница в цене серьёзная. Тридцать тысяч сверху — это много.' },
          { id: 't7', at: 112, speaker: 'employee', text: 'Смотрите: Pro служит в среднем на год дольше и продаётся дороже на вторичке. В пересчёте на месяц разница — около 800 рублей.', momentId: 'm2' },
          { id: 't8', at: 148, speaker: 'client', text: 'Логично. А если разобью? У меня руки не золотые.' },
          { id: 't9', at: 158, speaker: 'ai', text: 'Подсказка: сейчас идеальный момент предложить расширенную гарантию Стартех+ за 12 000 ₽.' },
          { id: 't10', at: 166, speaker: 'employee', text: 'Стекло здесь прочнее прошлого поколения, так что переживать особо не стоит.', momentId: 'm3' },
          { id: 't11', at: 402, speaker: 'employee', text: 'Отлично, оформляем Pro. К нему часто берут AirPods — шумодав в метро реально выручает, и они сейчас со скидкой при покупке в комплекте.', momentId: 'm4' },
          { id: 't12', at: 428, speaker: 'client', text: 'Давайте, беру. Как раз старые сломались.' },
        ],
        summary:
          'Сильная консультация: потребность выявлена до показа товара, возражение по цене снято через стоимость владения, чек увеличен наушниками. Единственная потеря — гарантия, о которой клиент спросил сам.',
        recommendations: [
          'Когда клиент говорит «а если разобью» — это прямой запрос на гарантию. Отвечайте предложением, а не успокоением.',
          'Приём со стоимостью владения сработал: зафиксируйте формулировку и используйте на всех Pro-моделях.',
        ],
      },
      {
        id: 'd2',
        employeeId: 'e3',
        pointId: 'p1',
        startedAt: '2026-07-29T13:02:00',
        durationSec: 268,
        outcome: 'lost',
        revenue: 0,
        scriptScore: 52,
        responseSec: 8.4,
        category: 'Выбор техники',
        topic: 'Выбор смартфона',
        items: [],
        helpRequests: 1,
        hasCue: true,
        wave: makeWave(202),
        moments: [
          { id: 'm5', at: 9, type: 'miss', title: 'Сразу повёл к витрине', note: 'Этап выявления потребности пропущен полностью. Дальше весь разговор строился на догадках.' },
          { id: 'm6', at: 41, type: 'miss', title: 'Не смог объяснить отличия Pro', note: 'Пауза 9 секунд, затем общий ответ «он мощнее». Клиент потерял доверие к консультации.' },
          { id: 'm7', at: 58, type: 'help', title: 'Позвал старшего консультанта', note: 'Обращение к коллеге вместо поиска в базе. Клиент ждал 40 секунд.' },
          { id: 'm8', at: 72, type: 'miss', title: 'Отпустил клиента без следующего шага', note: 'Не предложил ни отложить товар, ни рассрочку, ни контакт. Сделка ушла в ноль.' },
        ],
        transcript: [
          { id: 't20', at: 6, speaker: 'client', text: 'Добрый день, подскажите по айфонам.' },
          { id: 't21', at: 11, speaker: 'employee', text: 'Здравствуйте, вот тут вся линейка, смотрите.', momentId: 'm5' },
          { id: 't22', at: 18, speaker: 'ai', text: 'Подсказка: спросите, как клиент будет пользоваться телефоном. Без этого выбор между 15 и Pro не обосновать.' },
          { id: 't23', at: 96, speaker: 'client', text: 'А чем Pro отличается? Стоит ли переплачивать?' },
          { id: 't24', at: 110, speaker: 'employee', text: 'Ну… он мощнее. Процессор новее.', momentId: 'm6' },
          { id: 't25', at: 118, speaker: 'ai', text: 'Подсказка: титановый корпус, 5x телефото, ProMotion 120 Гц, кнопка действия. Назовите два отличия под задачу клиента.' },
          { id: 't26', at: 152, speaker: 'employee', text: 'Секунду, я позову старшего, он точнее расскажет.', momentId: 'm7' },
          { id: 't27', at: 158, speaker: 'colleague', text: 'Извините за ожидание, сейчас подойду — у меня клиент на кассе.' },
          { id: 't28', at: 176, speaker: 'client', text: 'Понятно. Я, наверное, ещё посмотрю и подумаю.' },
          { id: 't29', at: 184, speaker: 'employee', text: 'Хорошо, заходите.', momentId: 'm8' },
          { id: 't30', at: 190, speaker: 'ai', text: 'Подсказка: предложите отложить модель на 24 часа или рассчитать рассрочку — это возвращает до 30 % ушедших клиентов.' },
        ],
        summary:
          'Консультация потеряна на знании продукта. Клиент задал главный вопрос линейки — «чем отличается Pro» — и не получил ответа. Подсказка в гарнитуру пришла, но не была использована; вместо базы знаний сотрудник позвал коллегу.',
        recommendations: [
          'Выучите два отличия Pro под каждый тип клиента: для съёмки — телефото и стабилизация, для игр — ProMotion 120 Гц.',
          'Никогда не заканчивайте консультацию словом «заходите». Всегда следующий шаг: отложить товар, посчитать рассрочку, взять контакт.',
          'Ответ был в базе знаний — искать там быстрее, чем ждать освободившегося коллегу.',
        ],
      },
      {
        id: 'd3',
        employeeId: 'e2',
        pointId: 'p1',
        startedAt: '2026-07-29T15:40:00',
        durationSec: 394,
        outcome: 'success',
        revenue: 88_000,
        scriptScore: 86,
        responseSec: 3.4,
        category: 'Trade-in',
        topic: 'Обмен старого телефона',
        items: [{ name: 'iPhone 15 128 ГБ', qty: 1, price: 88_000 }],
        helpRequests: 0,
        hasCue: true,
        wave: makeWave(303),
        moments: [
          { id: 'm9', at: 22, type: 'win', title: 'Предложила trade-in первой', note: 'Не дожидаясь возражения по цене, показала, что старый телефон закроет часть суммы.' },
          { id: 'm10', at: 58, type: 'win', title: 'Честно назвала состояние аппарата', note: 'Оценка без завышенных ожиданий — клиент не почувствовал подвоха при финальной сумме.' },
          { id: 'm11', at: 88, type: 'miss', title: 'Не предложила чехол и стекло', note: 'Классическая связка к новому телефону. Средний чек по точке теряет ≈ 3 500 ₽ на таких консультациях.' },
        ],
        transcript: [
          { id: 't40', at: 10, speaker: 'client', text: 'Хочу поменять телефон, но бюджет ограничен.' },
          { id: 't41', at: 26, speaker: 'employee', text: 'А что у вас сейчас? Мы принимаем в trade-in — это сразу минус часть суммы.', momentId: 'm9' },
          { id: 't42', at: 84, speaker: 'employee', text: 'По вашему аппарату — экран с царапиной, поэтому оценка будет 21 000, а не 26 000. Скажу честно сразу, чтобы на кассе не было сюрприза.', momentId: 'm10' },
          { id: 't43', at: 210, speaker: 'client', text: 'Нормально, берём.' },
          { id: 't44', at: 340, speaker: 'ai', text: 'Подсказка: к новому аппарату предложите защитное стекло и чехол — результативность связки 61 %.' },
          { id: 't45', at: 356, speaker: 'employee', text: 'Отлично, идём на кассу.', momentId: 'm11' },
        ],
        summary:
          'Уверенная работа с trade-in: предложение прозвучало до возражения о цене, оценка дана честно. Потеряна только связка аксессуаров в конце.',
        recommendations: [
          'Добавьте стекло и чехол в момент оформления — это одно предложение и +3 500 ₽ к чеку.',
          'Приём «честная оценка вслух» снижает отказы на кассе. Продолжайте так же.',
        ],
      },
      {
        id: 'd4',
        employeeId: 'e5',
        pointId: 'p2',
        startedAt: '2026-07-28T18:11:00',
        durationSec: 331,
        outcome: 'lost',
        revenue: 0,
        scriptScore: 61,
        responseSec: 5.6,
        category: 'Цена и рассрочка',
        topic: 'Ожидание скидки',
        items: [],
        helpRequests: 0,
        hasCue: true,
        wave: makeWave(404),
        moments: [
          { id: 'm12', at: 30, type: 'miss', title: 'Согласился с «подожду скидку»', note: 'Вместо работы с ценностью подтвердил, что стоит подождать. Клиент ушёл с готовым решением не покупать.' },
          { id: 'm13', at: 74, type: 'miss', title: 'Не рассчитал рассрочку', note: 'Клиент дважды упомянул бюджет — прямой сигнал к рассрочке 0-0-12.' },
        ],
        transcript: [
          { id: 't50', at: 14, speaker: 'client', text: 'Дороговато. Может, к осени подешевеет?' },
          { id: 't51', at: 28, speaker: 'employee', text: 'Ну, возможно, ближе к ноябрю будут акции.', momentId: 'm12' },
          { id: 't52', at: 36, speaker: 'ai', text: 'Подсказка: не подтверждайте ожидание скидки. Предложите рассрочку 0-0-12 — платёж 11 600 ₽ в месяц.' },
          { id: 't53', at: 152, speaker: 'client', text: 'Тогда я подожду, спасибо.' },
          { id: 't54', at: 160, speaker: 'employee', text: 'Хорошо, до свидания.', momentId: 'm13' },
        ],
        summary:
          'Сделка проиграна одной фразой. Подтверждение будущей скидки — самая дорогая ошибка на сети: 49 подобных консультаций за месяц, результативность 8 %.',
        recommendations: [
          'На «подожду скидку» отвечайте рассрочкой, а не согласием. Платёж в месяц звучит меньше, чем цена целиком.',
          'Пройдите тест «Работа с ценовыми возражениями» — назначен РОПом.',
        ],
      },
      {
        id: 'd5',
        employeeId: 'e6',
        pointId: 'p3',
        startedAt: '2026-07-28T12:35:00',
        durationSec: 604,
        outcome: 'success',
        revenue: 71_000,
        scriptScore: 93,
        responseSec: 3.0,
        category: 'Выбор техники',
        topic: 'Умный дом',
        items: [
          { name: 'Робот-пылесос Dreame', qty: 1, price: 39_000 },
          { name: 'Умные лампы, комплект', qty: 4, price: 8_000 },
        ],
        helpRequests: 0,
        hasCue: true,
        wave: makeWave(505),
        moments: [
          { id: 'm14', at: 18, type: 'win', title: 'Продала сценарий, а не устройство', note: 'Начала с «как проходит ваш день», собрала комплект под быт клиента.' },
          { id: 'm15', at: 62, type: 'win', title: 'Сняла страх сложной установки', note: 'Показала настройку на своём телефоне за 30 секунд — главный барьер умного дома.' },
          { id: 'm16', at: 91, type: 'miss', title: 'Консультация затянулась до 10 минут', note: 'Последние 3 минуты — повтор уже сказанного. Клиент был готов купить раньше.' },
        ],
        transcript: [
          { id: 't60', at: 20, speaker: 'client', text: 'Присматриваю пылесос, но не знаю, нужен ли робот.' },
          { id: 't61', at: 34, speaker: 'employee', text: 'Расскажите, как обычно проходит уборка? Кто дома днём, есть ли животные?', momentId: 'm14' },
          { id: 't62', at: 208, speaker: 'employee', text: 'Смотрите, настраивается вот так — тридцать секунд с телефона, я покажу на своём.', momentId: 'm15' },
          { id: 't63', at: 420, speaker: 'client', text: 'Здорово, берём. И лампы тоже давайте.' },
          { id: 't64', at: 470, speaker: 'ai', text: 'Подсказка: клиент согласился. Можно переходить к оформлению.' },
          { id: 't65', at: 540, speaker: 'employee', text: 'И ещё раз про режимы уборки — их здесь четыре…', momentId: 'm16' },
        ],
        summary:
          'Образцовая продажа сценарием: комплект собран под быт клиента, барьер установки снят демонстрацией. Единственное — консультацию стоило закрыть на четыре минуты раньше.',
        recommendations: [
          'Клиент сказал «берём» на 7-й минуте — дальше идёт риск передумать. Закрывайте сразу.',
          'Демонстрация настройки с телефона — сильный приём. Стоит показать его коллегам на планёрке.',
        ],
      },
      {
        id: 'd6',
        employeeId: 'e8',
        pointId: 'p4',
        startedAt: '2026-07-28T16:20:00',
        durationSec: 212,
        outcome: 'success',
        revenue: 23_000,
        scriptScore: 68,
        responseSec: 4.1,
        category: 'Выбор техники',
        topic: 'Бюджетный смартфон',
        items: [{ name: 'Xiaomi Redmi Note', qty: 1, price: 23_000 }],
        helpRequests: 1,
        hasCue: true,
        wave: makeWave(606),
        moments: [
          { id: 'm17', at: 14, type: 'miss', title: 'Сразу увёл в нижний сегмент', note: 'На «что подешевле» показал самую дешёвую модель, не выяснив реальный бюджет.' },
          { id: 'm18', at: 48, type: 'help', title: 'Уточнял наличие у склада', note: 'Ответ по остаткам был в базе — обращение к складу заняло 50 секунд.' },
          { id: 'm19', at: 70, type: 'win', title: 'Быстро закрыл сделку', note: 'От вопроса до кассы — 3,5 минуты. В час пик это позволяет обслужить больше клиентов.' },
        ],
        transcript: [
          { id: 't70', at: 8, speaker: 'client', text: 'Что есть подешевле, но чтобы нормально работало?' },
          { id: 't71', at: 16, speaker: 'employee', text: 'Вот эта за 23 тысячи, берут часто.', momentId: 'm17' },
          { id: 't72', at: 24, speaker: 'ai', text: 'Подсказка: уточните бюджет вилкой — «до 30 или до 50?». «Подешевле» редко значит «самое дешёвое».' },
          { id: 't73', at: 102, speaker: 'employee', text: 'Секунду, уточню на складе, есть ли синий цвет.', momentId: 'm18' },
          { id: 't74', at: 150, speaker: 'employee', text: 'Оформляем? Касса свободна.', momentId: 'm19' },
        ],
        summary:
          'Сделка есть, но чек ниже сети на 19 %. Причина системная: «подешевле» трактуется как «самое дешёвое» без уточнения вилки бюджета.',
        recommendations: [
          'Уточняйте бюджет вилкой: «Ориентируетесь до 30 или до 50?». Это поднимает чек без давления.',
          'Остатки по цветам есть в базе знаний — не нужно звонить на склад.',
        ],
      },
    ],
    tests: [
      {
        id: 'ts1',
        title: 'Линейка iPhone 15: чем Pro отличается',
        description: 'Собран по 39 консультациям, где не удалось объяснить отличия Pro-моделей.',
        source: 'errors',
        sourceDetail: 'Ошибки консультантов · Ассортимент и характеристики',
        createdAt: '2026-07-24',
        createdBy: 'Анастасия Наумкина',
        deadline: '2026-08-05',
        passScore: 70,
        questions: [
          {
            id: 'q1',
            question: 'Клиент много снимает детей в движении. Какие два отличия Pro назвать в первую очередь?',
            options: [
              'Титановый корпус и вес',
              '5x телефото и улучшенная стабилизация',
              'Более ёмкий аккумулятор и быстрая зарядка',
              'Экран 120 Гц и кнопка действия',
            ],
            correct: 1,
            explain: 'Под задачу «снимать движение» работают оптика и стабилизация. Остальные отличия реальны, но не отвечают на запрос клиента.',
            source: 'Характеристики',
          },
          {
            id: 'q2',
            question: 'Клиент говорит: «Разница 30 тысяч — это много». Что сделать?',
            options: [
              'Согласиться и предложить обычную модель',
              'Перевести на стоимость владения: срок службы и цена на вторичке',
              'Сказать, что скоро будет акция',
              'Промолчать и дать подумать',
            ],
            correct: 1,
            explain: 'Перевод цены в стоимость владения снимает возражение без скидки. Этот приём даёт лучший результат на сети.',
            source: 'Скрипт продаж',
          },
          {
            id: 'q3',
            question: 'Что означает ProMotion 120 Гц для покупателя простыми словами?',
            options: [
              'Экран ярче на солнце',
              'Изображение плавнее — заметно в играх и при прокрутке',
              'Батарея держит дольше',
              'Быстрее заряжается',
            ],
            correct: 1,
            explain: 'Говорите выгодой, а не характеристикой: «плавнее», а не «120 герц».',
            source: 'Характеристики',
          },
          {
            id: 'q4',
            question: 'Клиент спрашивает: «А если разобью?». Это сигнал к чему?',
            options: [
              'Успокоить — стекло прочное',
              'Предложить расширенную гарантию Стартех+',
              'Показать чехлы',
              'Рассказать про сервисный центр',
            ],
            correct: 1,
            explain: 'Это прямой запрос на защиту покупки. Чехол — дополнение, но гарантия отвечает на вопрос точнее и добавляет 12 000 ₽ к чеку.',
            source: 'Доставка и гарантия',
          },
        ],
        assignedTo: ['e3', 'e5', 'e7', 'e8'],
        results: { e5: 75, e8: 50 },
      },
      {
        id: 'ts2',
        title: 'Работа с ценовыми возражениями',
        description: 'Собран из скриптов компании и 49 консультаций, закрытых фразой «подожду скидку».',
        source: 'questions',
        sourceDetail: 'Частые вопросы · Цена и рассрочка',
        createdAt: '2026-07-20',
        createdBy: 'Анастасия Наумкина',
        deadline: '2026-08-01',
        passScore: 70,
        questions: [
          {
            id: 'q5',
            question: 'Клиент: «Подожду, когда подешевеет». Лучший ответ?',
            options: [
              '«Да, ближе к ноябрю бывают акции»',
              '«Давайте посчитаю рассрочку — выйдет 11 600 ₽ в месяц»',
              '«Цена вряд ли изменится»',
              '«Могу отложить на день»',
            ],
            correct: 1,
            explain: 'Рассрочка меняет масштаб суммы и сохраняет сделку сегодня. Подтверждение будущей скидки — прямая потеря клиента.',
            source: 'Скрипт продаж',
          },
          {
            id: 'q6',
            question: 'Клиент говорит «подешевле». Что уточнить?',
            options: [
              'Ничего, показать самое дешёвое',
              'Вилку бюджета: «до 30 или до 50?»',
              'Спросить, кто оплачивает покупку',
              'Предложить кредит',
            ],
            correct: 1,
            explain: '«Подешевле» — не «самое дешёвое». Вилка поднимает средний чек и не давит на клиента.',
            source: 'Скрипт продаж',
          },
          {
            id: 'q7',
            question: 'Когда предлагать trade-in?',
            options: [
              'После возражения о цене',
              'До разговора о цене, как способ уменьшить сумму',
              'Только если клиент спросил сам',
              'На кассе',
            ],
            correct: 1,
            explain: 'Trade-in, предложенный заранее, снимает возражение до того, как оно прозвучало. Результативность таких консультаций — 34 %.',
            source: 'Акции',
          },
        ],
        assignedTo: ['e3', 'e5', 'e7', 'e8'],
        results: { e5: 67, e3: 33 },
      },
      {
        id: 'ts3',
        title: 'Стандарт консультации Стартех',
        description: 'Загружен из файла «Скрипт продаж v4.docx». Базовый тест онбординга.',
        source: 'file',
        sourceDetail: 'Файл · Скрипт продаж v4.docx',
        createdAt: '2026-07-08',
        createdBy: 'Анастасия Наумкина',
        deadline: '2026-07-31',
        passScore: 70,
        questions: [
          {
            id: 'q8',
            question: 'С чего начинается консультация по стандарту?',
            options: [
              'С показа витрины',
              'С вопроса о задаче клиента',
              'С рассказа об акциях',
              'С предложения помощи «что-то подсказать?»',
            ],
            correct: 1,
            explain: 'Выявление потребности до показа товара — этап №1. Его пропуск снижает результативность вдвое.',
            source: 'Скрипт продаж',
          },
          {
            id: 'q9',
            question: 'Клиент уходит подумать. Что обязательно сделать?',
            options: [
              'Попрощаться',
              'Назначить следующий шаг: отложить товар, посчитать рассрочку или взять контакт',
              'Дать визитку',
              'Предложить скидку',
            ],
            correct: 1,
            explain: 'Следующий шаг возвращает до 30 % ушедших клиентов. Без него сделка закрыта в ноль.',
            source: 'Скрипт продаж',
          },
          {
            id: 'q10',
            question: 'В какой момент предлагать аксессуары?',
            options: [
              'В начале разговора',
              'Когда клиент уже согласился на основной товар',
              'На кассе после оплаты',
              'Не предлагать, если клиент не спросил',
            ],
            correct: 1,
            explain: 'Момент принятого решения — пик готовности. Именно там связка «телефон + наушники» даёт 61 % результативности.',
            source: 'Скрипт продаж',
          },
        ],
        assignedTo: ['e3', 'e7'],
        results: { e3: 67, e7: 100 },
      },
    ],
    faq: [
      {
        id: 'f1',
        question: 'Чем Pro отличается от обычной модели?',
        category: 'Выбор техники',
        count: 312,
        trend: 8,
        conversion: 24,
        avgResponseSec: 5.4,
        bestAnswer: 'Называть два отличия под задачу клиента: для съёмки — 5x телефото и стабилизация, для игр — экран 120 Гц.',
        weakSpot: 'Данил Ефремов, Тимур Валиев — общий ответ «он мощнее», результативность 9–21 %.',
        source: 'Характеристики',
        updatedAt: '2026-07-22',
        status: 'published',
        verified: true,
      },
      {
        id: 'f2',
        question: 'Есть ли рассрочка без переплаты?',
        category: 'Цена и рассрочка',
        count: 287,
        trend: 14,
        conversion: 22,
        avgResponseSec: 4.1,
        bestAnswer: 'Сразу назвать платёж в месяц, а не условия программы: «11 600 ₽ в месяц на год».',
        weakSpot: 'В 41 % консультаций сотрудник описывает условия, но не называет ежемесячный платёж.',
        source: 'Акции',
        updatedAt: '2026-07-26',
        status: 'published',
        verified: true,
      },
      {
        id: 'f3',
        question: 'Когда будет скидка?',
        category: 'Цена и рассрочка',
        count: 174,
        trend: 21,
        conversion: 8,
        avgResponseSec: 3.2,
        bestAnswer: 'Не подтверждать будущую скидку. Переводить на рассрочку или trade-in.',
        weakSpot: 'Самый дорогой вопрос сети: 174 консультации, результативность 8 %. Основной источник — Метрополис и Казань.',
        source: 'Скрипты продаж',
        updatedAt: '2026-07-18',
        status: 'published',
        verified: true,
      },
      {
        id: 'f4',
        question: 'Можно ли обменять старый телефон?',
        category: 'Trade-in',
        count: 143,
        trend: -4,
        conversion: 34,
        avgResponseSec: 4.8,
        bestAnswer: 'Честно называть оценку вслух до кассы, объясняя, что влияет на сумму.',
        weakSpot: 'Работает хорошо. Стоит перенести приём Марии Соколовой на остальные точки.',
        source: 'Акции',
        updatedAt: '2026-07-25',
        status: 'published',
        verified: true,
      },
      {
        id: 'f5',
        question: 'Сколько держит батарея?',
        category: 'Выбор техники',
        count: 128,
        trend: 3,
        conversion: 19,
        avgResponseSec: 6.2,
        bestAnswer: 'Отвечать сценарием дня клиента: «на день активного использования с запасом».',
        weakSpot: 'Консультанты называют мАч — клиенту это ничего не говорит.',
        source: 'Характеристики',
        updatedAt: '2026-06-14',
        status: 'outdated',
        verified: false,
      },
      {
        id: 'f6',
        question: 'Что подешевле, но нормальное?',
        category: 'Цена и рассрочка',
        count: 119,
        trend: 6,
        conversion: 21,
        avgResponseSec: 3.8,
        bestAnswer: 'Уточнять вилку бюджета: «до 30 или до 50?» — и показывать две модели на выбор.',
        weakSpot: 'Казань: сразу показывают самую дешёвую модель, чек ниже сети на 19 %.',
        source: 'Скрипты продаж',
        updatedAt: '2026-07-20',
        status: 'published',
        verified: true,
      },
      {
        id: 'f7',
        question: 'Есть ли этот цвет в наличии?',
        category: 'Наличие',
        count: 96,
        trend: 11,
        conversion: 27,
        avgResponseSec: 9.6,
        bestAnswer: 'Смотреть остатки в базе Onvy, а не звонить на склад — ответ есть в карточке товара.',
        weakSpot: 'Казань и Метрополис: 44 и 81 обращение к складу вместо поиска в базе.',
        source: 'Остатки',
        updatedAt: '2026-07-29',
        status: 'published',
        verified: true,
      },
    ],
    scriptErrors: [
      { id: 'se1', label: 'Пропущено выявление потребности', count: 186, costPerMonth: 940_000, employees: ['Данил Ефремов', 'Рустам Хайруллин', 'Тимур Валиев'] },
      { id: 'se2', label: 'Нет следующего шага при уходе клиента', count: 151, costPerMonth: 720_000, employees: ['Данил Ефремов', 'Тимур Валиев'] },
      { id: 'se3', label: 'Не предложены аксессуары', count: 134, costPerMonth: 468_000, employees: ['Мария Соколова', 'Данил Ефремов', 'Никита Ларин'] },
      { id: 'se4', label: 'Подтверждение будущей скидки', count: 49, costPerMonth: 610_000, employees: ['Тимур Валиев', 'Рустам Хайруллин'] },
      { id: 'se5', label: 'Не предложена расширенная гарантия', count: 92, costPerMonth: 384_000, employees: ['Артём Кузнецов', 'Ольга Панина', 'Елена Бортник'] },
    ],
    knowledgeFiles: [
      { id: 'kf1', name: 'Ассортимент_июль.xlsx', sizeKb: 842, uploadedAt: '2026-07-01', kind: 'catalog', categories: ['Смартфоны', 'Ноутбуки', 'Аксессуары'], records: 1284 },
      { id: 'kf2', name: 'Скрипт продаж v4.docx', sizeKb: 96, uploadedAt: '2026-07-08', kind: 'scripts', categories: ['Этапы консультации', 'Возражения'], records: 46 },
      { id: 'kf3', name: 'Остатки_по_точкам.csv', sizeKb: 318, uploadedAt: '2026-07-29', kind: 'stock', categories: ['Наличие'], records: 3960 },
    ],
    pilot: {
      startedAt: '2026-06-15',
      weeks: 6,
      scope: '4 точки · 8 консультантов',
      goals: [
        'Сократить срок выхода стажёра на самостоятельную работу',
        'Поднять выполнение скрипта до 85 % по всей сети',
        'Убрать подтверждение будущих скидок в разговоре о цене',
        'Снизить обращения к складу за данными, которые есть в базе',
      ],
      metrics: [
        { key: 'responseSec', label: 'Скорость ответа', before: 7.4, during: 4.4, unit: 'sec', better: 'down' },
        { key: 'autonomy', label: 'Решено самостоятельно', before: 61, during: 77, unit: 'pct', better: 'up' },
        { key: 'helpRequests', label: 'Обращения к коллегам и складу', before: 812, during: 559, unit: 'count', better: 'down' },
        { key: 'scriptCompliance', label: 'Выполнение скрипта', before: 68, during: 83, unit: 'pct', better: 'up' },
        { key: 'errors', label: 'Ошибок в консультациях', before: 764, during: 612, unit: 'count', better: 'down' },
        { key: 'training', label: 'Прогресс обучения', before: 34, during: 86, unit: 'pct', better: 'up' },
        { key: 'badgeCoverage', label: 'Покрытие бейджами', before: 0, during: 75, unit: 'pct', better: 'up' },
        { key: 'avgCheck', label: 'Средний чек', before: 36_100, during: 39_607, unit: 'money', better: 'up', external: true },
        { key: 'conversion', label: 'Результативность', before: 15.8, during: 18.4, unit: 'pct', better: 'up', external: true },
      ],
    },
    adaptation: {
      daysToSolo: 14,
      daysToSoloBefore: 38,
      requiredModules: 3,
      completion: 88,
      firstCheckScore: 58,
      repeatedErrors: 21,
      noviceHelpPerShift: 5.1,
      earlyCompliance: 71,
    },
    bestPractices: [
      {
        id: 'ebp1',
        employeeId: 'e1',
        pointId: 'p1',
        title: 'Цена через стоимость владения',
        quote: 'Pro служит на год дольше и дороже на вторичке. В пересчёте на месяц разница — около 800 рублей.',
        effect: 'Возражение «дорого» снимается за 40 секунд без скидки.',
        category: 'Цена и рассрочка',
        dialogId: 'd1',
        inTraining: true,
      },
      {
        id: 'ebp2',
        employeeId: 'e2',
        pointId: 'p1',
        title: 'Честная оценка trade-in вслух',
        quote: 'Экран с царапиной, поэтому оценка 21 000, а не 26 000. Скажу сразу, чтобы на кассе не было сюрприза.',
        effect: 'Результативность trade-in 34 % — лучший показатель сети, отказов на кассе нет.',
        category: 'Trade-in',
        dialogId: 'd3',
        inTraining: false,
      },
      {
        id: 'ebp3',
        employeeId: 'e6',
        pointId: 'p3',
        title: 'Продажа сценарием, а не устройством',
        quote: 'Расскажите, как обычно проходит уборка? Кто дома днём, есть ли животные?',
        effect: 'Комплект собирается под быт клиента, допродажи 44 %.',
        category: 'Выбор техники',
        dialogId: 'd5',
        inTraining: false,
      },
    ],
    trainingOutcomes: [
      {
        testId: 'ts1',
        reason: '39 консультаций, где не удалось объяснить отличия Pro',
        origin: 'Разбор консультаций · категория «Выбор техники»',
        metric: 'proExplained',
        metricLabel: 'Отличия названы под задачу клиента',
        before: 34,
        after: 61,
        unit: 'pct',
        better: 'up',
        repeated: true,
      },
      {
        testId: 'ts2',
        reason: '49 консультаций закрыты фразой «подожду скидку»',
        origin: 'Частые вопросы · «Когда будет скидка?»',
        metric: 'discountConfirmed',
        metricLabel: 'Подтверждений будущей скидки',
        before: 49,
        after: 22,
        unit: 'count',
        better: 'down',
        repeated: false,
      },
      {
        testId: 'ts3',
        reason: 'Пропуск выявления потребности в 186 консультациях',
        origin: 'Скрипт продаж · загруженный документ',
        metric: 'scriptCompliance',
        metricLabel: 'Выполнение скрипта',
        before: 68,
        after: 83,
        unit: 'pct',
        better: 'up',
        repeated: false,
      },
    ],
  };
}
