import type { AppData } from '../types';
import { daily, makeWave } from './shared';

/** Демо-пространство «Чайхона №1» — первый пилот на ресторанном профиле. */
export function horecaSpace(): AppData {
  return {
    space: 'horeca',
    company: {
      id: 'ch1',
      name: 'Чайхона №1',
      industry: 'horeca',
      staffSize: '50–200',
      pointsPlanned: '3',
      city: 'Москва',
      joinCode: 'CHAYHONA-2026',
      createdAt: '2026-06-01',
    },
    points: [
      {
        id: 'r1',
        name: 'Чайхона №1 Новый Арбат',
        city: 'Москва',
        address: 'Новый Арбат, 21',
        zones: ['Основной зал', 'Веранда', 'Бар'],
        manager: 'Тимур Рахимов',
        staffCount: 3,
        badgesOnline: 3,
        plan: 7_400_000,
        revenue: 7_812_000,
        avgCheck: 3_240,
        interactions: 2411,
        conversion: 92.4,
        scriptCompliance: 86,
        training: 84,
        helpRequests: 318,
        industry: {
          itemsPerCheck: 4.6,
          drinkOffer: 71,
          dessertOffer: 38,
          compositionQuestions: 284,
          allergenQuestions: 96,
          kitchenEscalations: 214,
          orderCorrections: 41,
          stopListChecks: 176,
        },
      },
      {
        id: 'r2',
        name: 'Чайхона №1 Парк Горького',
        city: 'Москва',
        address: 'Крымский Вал, 9',
        zones: ['Основной зал', 'Летняя терраса'],
        manager: 'Алина Юсупова',
        staffCount: 2,
        badgesOnline: 2,
        plan: 6_100_000,
        revenue: 5_468_000,
        avgCheck: 2_910,
        interactions: 1879,
        conversion: 88.1,
        scriptCompliance: 78,
        training: 62,
        helpRequests: 402,
        industry: {
          itemsPerCheck: 3.8,
          drinkOffer: 54,
          dessertOffer: 21,
          compositionQuestions: 241,
          allergenQuestions: 118,
          kitchenEscalations: 296,
          orderCorrections: 74,
          stopListChecks: 92,
        },
      },
      {
        id: 'r3',
        name: 'Чайхона №1 Кутузовский',
        city: 'Москва',
        address: 'Кутузовский пр., 48',
        zones: ['Основной зал', 'Банкетный зал'],
        manager: 'Дамир Салимов',
        staffCount: 2,
        badgesOnline: 1,
        plan: 5_200_000,
        revenue: 5_344_000,
        avgCheck: 3_480,
        interactions: 1536,
        conversion: 90.7,
        scriptCompliance: 83,
        training: 79,
        helpRequests: 227,
        industry: {
          itemsPerCheck: 4.3,
          drinkOffer: 66,
          dessertOffer: 34,
          compositionQuestions: 198,
          allergenQuestions: 74,
          kitchenEscalations: 168,
          orderCorrections: 38,
          stopListChecks: 141,
        },
      },
    ],
    accounts: [
      {
        id: 'ca1',
        role: 'rop',
        name: 'Тимур Рахимов',
        email: 'rop@chayhona.ru',
        password: 'onvy2026',
        companyId: 'ch1',
        position: 'Директор по корпоративной культуре',
        focus: 'culture',
      },
      {
        id: 'ca2',
        role: 'employee',
        name: 'Аслан Каримов',
        email: 'aslan@chayhona.ru',
        password: 'onvy2026',
        companyId: 'ch1',
        pointId: 'r1',
        position: 'Старший официант',
        employeeId: 'w1',
      },
    ],
    employees: [
      {
        id: 'w1',
        name: 'Аслан Каримов',
        position: 'Старший официант',
        pointId: 'r1',
        hiredAt: '2024-05-20',
        onboarding: 100,
        level: 7,
        xp: 6180,
        badgeOnline: true,
        badgeBattery: 78,
        micQuality: 93,
        stats: {
          revenue: 2_984_000,
          deals: 921,
          dialogs: 968,
          avgCheck: 3_240,
          conversion: 95.1,
          scriptCompliance: 91,
          responseSec: 3.2,
          autonomy: 92,
          helpRequests: 74,
        },
        industry: {
          itemsPerCheck: 5.1,
          drinkOffer: 84,
          dessertOffer: 52,
          compositionQuestions: 112,
          allergenQuestions: 38,
          kitchenEscalations: 48,
          orderCorrections: 9,
          stopListChecks: 86,
        },
        daily: daily(11, 213_000),
        topItems: [
          { name: 'Люля-кебаб из баранины', qty: 184, revenue: 128_800 },
          { name: 'Плов по-фергански', qty: 156, revenue: 109_200 },
          { name: 'Чай узбекский, чайник', qty: 412, revenue: 164_800 },
          { name: 'Чак-чак', qty: 98, revenue: 39_200 },
        ],
        topRequests: [
          { label: 'Что посоветуете к мясу?', count: 148, conversion: 74 },
          { label: 'Из чего готовится это блюдо?', count: 112, conversion: 61 },
          { label: 'Насколько блюдо острое?', count: 86, conversion: 68 },
          { label: 'Есть ли в блюде орехи?', count: 38, conversion: 55 },
        ],
        strengths: [
          'Предлагает напиток в 84 % заказов — лучший показатель сети',
          'Всегда проверяет стоп-лист до подтверждения заказа',
          'По аллергенам никогда не отвечает по памяти — уточняет у кухни',
        ],
        growthAreas: [
          'Десерт предлагает только в половине заказов, хотя чек это выдерживает',
        ],
        trainingDone: 3,
        trainingTotal: 3,
      },
      {
        id: 'w2',
        name: 'Дилноза Рустамова',
        position: 'Официант',
        pointId: 'r1',
        hiredAt: '2025-11-04',
        onboarding: 100,
        level: 5,
        xp: 3940,
        badgeOnline: true,
        badgeBattery: 61,
        micQuality: 89,
        stats: {
          revenue: 2_641_000,
          deals: 848,
          dialogs: 912,
          avgCheck: 3_114,
          conversion: 93.0,
          scriptCompliance: 87,
          responseSec: 3.8,
          autonomy: 84,
          helpRequests: 118,
        },
        industry: {
          itemsPerCheck: 4.5,
          drinkOffer: 72,
          dessertOffer: 41,
          compositionQuestions: 98,
          allergenQuestions: 31,
          kitchenEscalations: 76,
          orderCorrections: 14,
          stopListChecks: 58,
        },
        daily: daily(22, 188_000),
        topItems: [
          { name: 'Плов по-фергански', qty: 142, revenue: 99_400 },
          { name: 'Салат «Ташкент»', qty: 118, revenue: 53_100 },
          { name: 'Айран', qty: 231, revenue: 46_200 },
        ],
        topRequests: [
          { label: 'Из чего готовится это блюдо?', count: 98, conversion: 58 },
          { label: 'Что посоветуете к мясу?', count: 76, conversion: 69 },
          { label: 'Это блюдо есть сегодня?', count: 58, conversion: 71 },
        ],
        strengths: ['Хорошо описывает блюда — гости чаще берут по её рекомендации'],
        growthAreas: [
          'Иногда отвечает по составу без проверки карты блюда',
          'Стоп-лист проверяет реже, чем нужно: 14 исправлений заказа за месяц',
        ],
        trainingDone: 2,
        trainingTotal: 3,
      },
      {
        id: 'w3',
        name: 'Санжар Убайдуллаев',
        position: 'Стажёр',
        pointId: 'r1',
        hiredAt: '2026-07-13',
        onboarding: 46,
        level: 2,
        xp: 720,
        badgeOnline: true,
        badgeBattery: 88,
        micQuality: 74,
        stats: {
          revenue: 1_186_000,
          deals: 402,
          dialogs: 531,
          avgCheck: 2_950,
          conversion: 75.7,
          scriptCompliance: 64,
          responseSec: 8.1,
          autonomy: 49,
          helpRequests: 126,
        },
        industry: {
          itemsPerCheck: 3.1,
          drinkOffer: 38,
          dessertOffer: 11,
          compositionQuestions: 74,
          allergenQuestions: 27,
          kitchenEscalations: 90,
          orderCorrections: 18,
          stopListChecks: 32,
        },
        daily: daily(33, 84_000),
        topItems: [
          { name: 'Люля-кебаб из баранины', qty: 61, revenue: 42_700 },
          { name: 'Чай узбекский, чайник', qty: 88, revenue: 35_200 },
        ],
        topRequests: [
          { label: 'Из чего готовится это блюдо?', count: 74, conversion: 41 },
          { label: 'Есть ли в блюде орехи?', count: 27, conversion: 38 },
          { label: 'Это блюдо есть сегодня?', count: 22, conversion: 45 },
        ],
        strengths: ['Доброжелателен, гости не жалуются на контакт'],
        growthAreas: [
          'Отвечал по составу блюда по памяти — критично для аллергенов',
          'Не проверяет стоп-лист: 18 исправлений заказа за месяц',
          'Напиток предлагает только в 38 % заказов при норме 70 %',
        ],
        trainingDone: 0,
        trainingTotal: 3,
      },
      {
        id: 'w4',
        name: 'Алина Юсупова',
        position: 'Старший официант',
        pointId: 'r2',
        hiredAt: '2024-09-12',
        onboarding: 100,
        level: 6,
        xp: 5240,
        badgeOnline: true,
        badgeBattery: 52,
        micQuality: 90,
        stats: {
          revenue: 3_012_000,
          deals: 986,
          dialogs: 1044,
          avgCheck: 3_054,
          conversion: 94.4,
          scriptCompliance: 88,
          responseSec: 3.5,
          autonomy: 88,
          helpRequests: 132,
        },
        industry: {
          itemsPerCheck: 4.4,
          drinkOffer: 74,
          dessertOffer: 36,
          compositionQuestions: 124,
          allergenQuestions: 52,
          kitchenEscalations: 98,
          orderCorrections: 21,
          stopListChecks: 62,
        },
        daily: daily(44, 215_000),
        topItems: [
          { name: 'Шашлык из телятины', qty: 168, revenue: 151_200 },
          { name: 'Лимонад домашний', qty: 284, revenue: 79_520 },
          { name: 'Чак-чак', qty: 76, revenue: 30_400 },
        ],
        topRequests: [
          { label: 'Что посоветуете к мясу?', count: 132, conversion: 71 },
          { label: 'Насколько блюдо острое?', count: 94, conversion: 64 },
          { label: 'Есть ли в блюде орехи?', count: 52, conversion: 51 },
        ],
        strengths: ['Держит стандарт на 88 %', 'Уверенно работает с банкетными заказами'],
        growthAreas: ['Десерт предлагает в трети заказов — резерв по чеку'],
        trainingDone: 3,
        trainingTotal: 3,
      },
      {
        id: 'w5',
        name: 'Рустам Ниязов',
        position: 'Официант',
        pointId: 'r2',
        hiredAt: '2026-03-02',
        onboarding: 68,
        level: 3,
        xp: 1810,
        badgeOnline: true,
        badgeBattery: 34,
        micQuality: 79,
        stats: {
          revenue: 2_456_000,
          deals: 742,
          dialogs: 835,
          avgCheck: 2_764,
          conversion: 88.9,
          scriptCompliance: 71,
          responseSec: 6.4,
          autonomy: 58,
          helpRequests: 270,
        },
        industry: {
          itemsPerCheck: 3.4,
          drinkOffer: 41,
          dessertOffer: 14,
          compositionQuestions: 117,
          allergenQuestions: 66,
          kitchenEscalations: 198,
          orderCorrections: 53,
          stopListChecks: 30,
        },
        daily: daily(55, 175_000),
        topItems: [
          { name: 'Плов по-фергански', qty: 134, revenue: 93_800 },
          { name: 'Чай узбекский, чайник', qty: 196, revenue: 78_400 },
        ],
        topRequests: [
          { label: 'Это блюдо есть сегодня?', count: 88, conversion: 52 },
          { label: 'Из чего готовится это блюдо?', count: 117, conversion: 47 },
          { label: 'Есть ли в блюде орехи?', count: 66, conversion: 39 },
        ],
        strengths: ['Быстро принимает заказ в час пик'],
        growthAreas: [
          '198 обращений к кухне за месяц — ответы есть в карте блюд',
          '53 исправления заказа: стоп-лист проверяется в последний момент',
          'Напиток предлагает в 41 % заказов при норме 70 %',
        ],
        trainingDone: 1,
        trainingTotal: 3,
      },
      {
        id: 'w6',
        name: 'Дамир Салимов',
        position: 'Старший официант',
        pointId: 'r3',
        hiredAt: '2025-01-28',
        onboarding: 100,
        level: 6,
        xp: 4620,
        badgeOnline: true,
        badgeBattery: 66,
        micQuality: 91,
        stats: {
          revenue: 3_128_000,
          deals: 874,
          dialogs: 936,
          avgCheck: 3_579,
          conversion: 93.4,
          scriptCompliance: 89,
          responseSec: 3.3,
          autonomy: 90,
          helpRequests: 96,
        },
        industry: {
          itemsPerCheck: 4.8,
          drinkOffer: 78,
          dessertOffer: 44,
          compositionQuestions: 108,
          allergenQuestions: 41,
          kitchenEscalations: 68,
          orderCorrections: 12,
          stopListChecks: 94,
        },
        daily: daily(66, 223_000),
        topItems: [
          { name: 'Каре ягнёнка', qty: 96, revenue: 172_800 },
          { name: 'Вино домашнее, бокал', qty: 218, revenue: 108_600 },
          { name: 'Чак-чак', qty: 84, revenue: 33_600 },
        ],
        topRequests: [
          { label: 'Что посоветуете к мясу?', count: 118, conversion: 79 },
          { label: 'Насколько блюдо острое?', count: 72, conversion: 66 },
        ],
        strengths: ['Лучший средний чек сети за счёт напитков к горячему'],
        growthAreas: ['На банкетах реже проверяет аллергены заранее'],
        trainingDone: 3,
        trainingTotal: 3,
      },
      {
        id: 'w7',
        name: 'Мадина Артыкова',
        position: 'Официант',
        pointId: 'r3',
        hiredAt: '2026-05-19',
        onboarding: 72,
        level: 3,
        xp: 1520,
        badgeOnline: false,
        badgeBattery: 8,
        micQuality: 70,
        stats: {
          revenue: 2_216_000,
          deals: 618,
          dialogs: 704,
          avgCheck: 3_100,
          conversion: 87.8,
          scriptCompliance: 76,
          responseSec: 5.9,
          autonomy: 63,
          helpRequests: 131,
        },
        industry: {
          itemsPerCheck: 3.7,
          drinkOffer: 52,
          dessertOffer: 22,
          compositionQuestions: 90,
          allergenQuestions: 33,
          kitchenEscalations: 100,
          orderCorrections: 26,
          stopListChecks: 47,
        },
        daily: daily(77, 158_000),
        topItems: [
          { name: 'Шашлык из телятины', qty: 88, revenue: 79_200 },
          { name: 'Айран', qty: 142, revenue: 28_400 },
        ],
        topRequests: [
          { label: 'Из чего готовится это блюдо?', count: 90, conversion: 49 },
          { label: 'Это блюдо есть сегодня?', count: 54, conversion: 58 },
        ],
        strengths: ['Растёт быстро: +9 п.п. по стандарту за две недели'],
        growthAreas: ['Не предлагает десерт', 'Часто уточняет состав у кухни вместо карты блюда'],
        trainingDone: 1,
        trainingTotal: 3,
      },
    ],
    kpis: [
      { id: 'ck1', employeeId: 'w1', metric: 'dessertOffer', target: 60, current: 52, period: 'week', setBy: 'Тимур Рахимов', note: 'Чак-чак к чаю — самый простой десерт для предложения' },
      { id: 'ck2', employeeId: 'w1', metric: 'deals', target: 32, current: 28, period: 'day', setBy: 'Тимур Рахимов' },
      { id: 'ck3', employeeId: 'w1', metric: 'avgCheck', target: 3_400, current: 3_240, period: 'week', setBy: 'Тимур Рахимов' },
      { id: 'ck4', employeeId: 'w2', metric: 'stopListChecks', target: 80, current: 58, period: 'week', setBy: 'Тимур Рахимов', note: 'Проверяем стоп-лист до подтверждения заказа, а не после' },
      { id: 'ck5', employeeId: 'w3', metric: 'drinkOffer', target: 70, current: 38, period: 'week', setBy: 'Тимур Рахимов', note: 'Напиток предлагаем каждому столу' },
      { id: 'ck6', employeeId: 'w3', metric: 'scriptCompliance', target: 80, current: 64, period: 'week', setBy: 'Тимур Рахимов' },
      { id: 'ck7', employeeId: 'w3', metric: 'autonomy', target: 70, current: 49, period: 'week', setBy: 'Тимур Рахимов', note: 'Состав блюда — в карте, а не у кухни' },
      { id: 'ck8', employeeId: 'w4', metric: 'dessertOffer', target: 50, current: 36, period: 'week', setBy: 'Тимур Рахимов' },
      { id: 'ck9', employeeId: 'w5', metric: 'kitchenEscalations', target: 90, current: 198, period: 'month', setBy: 'Тимур Рахимов', note: 'Снижаем обращения к кухне вдвое' },
      { id: 'ck10', employeeId: 'w5', metric: 'orderCorrections', target: 20, current: 53, period: 'month', setBy: 'Тимур Рахимов' },
      { id: 'ck11', employeeId: 'w6', metric: 'avgCheck', target: 3_600, current: 3_579, period: 'week', setBy: 'Тимур Рахимов' },
      { id: 'ck12', employeeId: 'w7', metric: 'drinkOffer', target: 70, current: 52, period: 'week', setBy: 'Тимур Рахимов' },
    ],
    dialogs: [
      {
        id: 'cd1',
        employeeId: 'w3',
        pointId: 'r1',
        startedAt: '2026-07-29T19:12:00',
        durationSec: 386,
        outcome: 'success',
        revenue: 2_640,
        scriptScore: 58,
        responseSec: 9.2,
        category: 'Аллергены',
        topic: 'Вопрос об аллергенах',
        items: [
          { name: 'Плов по-фергански', qty: 1, price: 700 },
          { name: 'Салат «Ташкент»', qty: 1, price: 450 },
          { name: 'Чай узбекский, чайник', qty: 1, price: 400 },
          { name: 'Лепёшка тандырная', qty: 2, price: 545 },
        ],
        helpRequests: 2,
        hasCue: true,
        wave: makeWave(701),
        moments: [
          { id: 'cm1', at: 14, type: 'miss', title: 'Ответил по аллергенам по памяти', note: 'Гость спросил про орехи. Официант ответил «вроде нет» — по аллергену догадка недопустима.' },
          { id: 'cm2', at: 26, type: 'win', title: 'Onvy остановил ответ', note: 'Подсказка потребовала подтвердить состав у кухни вместо ответа наугад.' },
          { id: 'cm3', at: 44, type: 'help', title: 'Уточнил состав у кухни', note: 'Правильное действие после подсказки, но заняло 70 секунд — гость ждал.' },
          { id: 'cm4', at: 68, type: 'miss', title: 'Не проверил стоп-лист', note: 'Долма была в стоп-листе с 18:40. Заказ пришлось исправлять после отправки на кухню.' },
          { id: 'cm5', at: 88, type: 'miss', title: 'Не предложил напиток к горячему', note: 'Стандарт: напиток предлагается каждому столу. Чек потерял примерно 400 ₽.' },
        ],
        transcript: [
          { id: 'ct1', at: 12, speaker: 'client', text: 'Скажите, а в плове есть орехи? У ребёнка аллергия, это важно.' },
          { id: 'ct2', at: 22, speaker: 'employee', text: 'Орехов вроде нет, там рис, морковь, баранина.', momentId: 'cm1' },
          {
            id: 'ct3',
            at: 30,
            speaker: 'ai',
            text: 'Информация не подтверждена. Вопрос касается аллергена — уточните состав у кухни или менеджера, не отвечайте по памяти.',
            momentId: 'cm2',
            unverified: true,
          },
          { id: 'ct4', at: 46, speaker: 'employee', text: 'Секунду, я уточню на кухне, чтобы сказать точно.', momentId: 'cm3' },
          { id: 'ct5', at: 92, speaker: 'colleague', text: 'В плове орехов нет. Но зира и барбарис есть — если аллергия на специи, предупредите гостя.' },
          { id: 'ct6', at: 108, speaker: 'employee', text: 'Уточнил у кухни: орехов в плове нет. Есть зира и барбарис — если на специи реакции нет, всё в порядке.' },
          { id: 'ct7', at: 126, speaker: 'client', text: 'Отлично, спасибо. Тогда плов и салат «Ташкент». И долму, пожалуйста.' },
          { id: 'ct8', at: 138, speaker: 'ai', text: 'Подсказка: долма в стоп-листе с 18:40. Предложите манты — ближайшая замена по вкусу и способу подачи.' },
          { id: 'ct9', at: 150, speaker: 'employee', text: 'Хорошо, записал: плов, «Ташкент», долма.', momentId: 'cm4' },
          { id: 'ct10', at: 232, speaker: 'employee', text: 'Извините, долмы сегодня нет — она закончилась. Могу предложить манты.' },
          { id: 'ct11', at: 248, speaker: 'client', text: 'Ладно, давайте просто лепёшку тогда.' },
          { id: 'ct12', at: 330, speaker: 'ai', text: 'Подсказка: к плову и мясу предложите айран или узбекский чай — берут в 71 % заказов.' },
          { id: 'ct13', at: 348, speaker: 'employee', text: 'Всё, заказ принят. Приятного вечера.', momentId: 'cm5' },
        ],
        summary:
          'Заказ состоялся, но обслуживание проседает по трём стандартам. Ключевое: на вопрос об аллергене прозвучал ответ по памяти — Onvy остановил его и потребовал подтверждения у кухни. Стоп-лист не проверен, поэтому заказ пришлось исправлять при госте. Напиток не предложен.',
        recommendations: [
          'Вопрос об аллергене — единственный случай, где догадка недопустима. Всегда подтверждайте состав у кухни или в карте блюда.',
          'Проверяйте стоп-лист до подтверждения заказа. Исправление при госте выглядит как ошибка ресторана.',
          'Напиток предлагается каждому столу. К плову — айран или чай, это 71 % согласий.',
        ],
      },
      {
        id: 'cd2',
        employeeId: 'w1',
        pointId: 'r1',
        startedAt: '2026-07-29T20:05:00',
        durationSec: 442,
        outcome: 'success',
        revenue: 5_180,
        scriptScore: 96,
        responseSec: 2.6,
        category: 'Рекомендация блюда',
        topic: 'Рекомендация к мясу',
        items: [
          { name: 'Люля-кебаб из баранины', qty: 2, price: 1_400 },
          { name: 'Каре ягнёнка', qty: 1, price: 1_800 },
          { name: 'Айран', qty: 2, price: 400 },
          { name: 'Чак-чак', qty: 2, price: 800 },
          { name: 'Чай узбекский, чайник', qty: 1, price: 400 },
        ],
        helpRequests: 0,
        hasCue: true,
        wave: makeWave(702),
        moments: [
          { id: 'cm6', at: 16, type: 'win', title: 'Уточнил предпочтения до рекомендации', note: 'Спросил про остроту и аппетит гостей — рекомендация попала точно.' },
          { id: 'cm7', at: 38, type: 'win', title: 'Проверил стоп-лист заранее', note: 'Сверился до того, как назвал блюда. Ни одного исправления заказа.' },
          { id: 'cm8', at: 62, type: 'win', title: 'Предложил напиток к мясу', note: 'Айран к люля — связка с самой высокой долей согласий.' },
          { id: 'cm9', at: 86, type: 'win', title: 'Довёл до десерта', note: 'Чак-чак к чаю в конце вечера. Чек вырос на 800 ₽.' },
        ],
        transcript: [
          { id: 'ct20', at: 14, speaker: 'client', text: 'Мы первый раз у вас. Что посоветуете из мяса?' },
          { id: 'ct21', at: 24, speaker: 'employee', text: 'Подскажите, острое любите? И насколько плотно хотите поесть — на компанию или каждому своё?', momentId: 'cm6' },
          { id: 'ct22', at: 44, speaker: 'ai', text: 'Подсказка: люля-кебаб из баранины и каре ягнёнка сегодня в наличии. Долма и казан-кебаб в стоп-листе.' },
          { id: 'ct23', at: 58, speaker: 'employee', text: 'Тогда рекомендую люля из баранины — она мягкая, не острая, и каре ягнёнка. Оба блюда сегодня есть, я проверил.', momentId: 'cm7' },
          { id: 'ct24', at: 168, speaker: 'employee', text: 'К баранине очень хорошо идёт айран — он сбивает жирность. Возьмёте пару?', momentId: 'cm8' },
          { id: 'ct25', at: 186, speaker: 'client', text: 'Давайте, звучит хорошо.' },
          { id: 'ct26', at: 342, speaker: 'employee', text: 'На десерт — чак-чак к узбекскому чаю. Порция небольшая, как раз после мяса.', momentId: 'cm9' },
          { id: 'ct27', at: 358, speaker: 'client', text: 'Отлично, берём.' },
        ],
        summary:
          'Эталонное обслуживание: предпочтения уточнены до рекомендации, стоп-лист проверен заранее, напиток и десерт предложены вовремя. Средний чек стола — 5 180 ₽ против 3 240 ₽ по точке.',
        recommendations: [
          'Связка «люля — айран — чак-чак» работает стабильно. Стоит показать её на планёрке как стандарт вечернего стола.',
          'Проверка стоп-листа до озвучивания рекомендации полностью убирает исправления заказа.',
        ],
      },
      {
        id: 'cd3',
        employeeId: 'w5',
        pointId: 'r2',
        startedAt: '2026-07-28T14:22:00',
        durationSec: 512,
        outcome: 'success',
        revenue: 2_180,
        scriptScore: 62,
        responseSec: 7.8,
        category: 'Состав блюда',
        topic: 'Вопрос по составу',
        items: [
          { name: 'Плов по-фергански', qty: 1, price: 700 },
          { name: 'Салат «Ташкент»', qty: 1, price: 450 },
          { name: 'Лепёшка тандырная', qty: 2, price: 545 },
          { name: 'Вода', qty: 1, price: 250 },
        ],
        helpRequests: 3,
        hasCue: true,
        wave: makeWave(703),
        moments: [
          { id: 'cm10', at: 18, type: 'help', title: 'Ушёл к кухне за составом салата', note: 'Состав есть в карте блюда. Обращение заняло 80 секунд.' },
          { id: 'cm11', at: 46, type: 'help', title: 'Второе обращение — по остроте', note: 'Уровень остроты указан в карте. Гость ждал повторно.' },
          { id: 'cm12', at: 74, type: 'miss', title: 'Не предложил напиток', note: 'Гость сам попросил воду. Предложение напитка — этап стандарта.' },
          { id: 'cm13', at: 92, type: 'help', title: 'Третье обращение — по времени подачи', note: 'Три обращения к кухне за один стол. Это верхний предел по сети.' },
        ],
        transcript: [
          { id: 'ct30', at: 16, speaker: 'client', text: 'А что входит в салат «Ташкент»?' },
          { id: 'ct31', at: 26, speaker: 'employee', text: 'Сейчас уточню на кухне.', momentId: 'cm10' },
          { id: 'ct32', at: 34, speaker: 'ai', text: 'Подсказка: состав есть в карте блюда — редька зелёная, отварная говядина, лук, яйцо, зелень. Уточнять у кухни не нужно.' },
          { id: 'ct33', at: 118, speaker: 'employee', text: 'Там редька, говядина, лук и яйцо.' },
          { id: 'ct34', at: 132, speaker: 'client', text: 'А плов острый?' },
          { id: 'ct35', at: 142, speaker: 'employee', text: 'Тоже уточню, секунду.', momentId: 'cm11' },
          { id: 'ct36', at: 150, speaker: 'ai', text: 'Подсказка: плов по-фергански — не острый, средняя насыщенность специй. Данные из карты блюда.' },
          { id: 'ct37', at: 288, speaker: 'client', text: 'Хорошо, плов, салат, лепёшку. И воду просто.' },
          { id: 'ct38', at: 302, speaker: 'employee', text: 'Принял.', momentId: 'cm12' },
          { id: 'ct39', at: 452, speaker: 'employee', text: 'Пойду узнаю, когда будет готово.', momentId: 'cm13' },
        ],
        summary:
          'Заказ принят, но три обращения к кухне за один стол. Все три ответа были в карте блюда, и Onvy давал их подсказкой. Напиток не предложен — гость попросил воду сам.',
        recommendations: [
          'Состав и острота есть в карте блюда. Обращение к кухне удлиняет обслуживание втрое.',
          'Напиток предлагаем до того, как гость попросит. Это этап стандарта, а не инициатива.',
        ],
      },
      {
        id: 'cd4',
        employeeId: 'w2',
        pointId: 'r1',
        startedAt: '2026-07-28T13:40:00',
        durationSec: 298,
        outcome: 'success',
        revenue: 3_820,
        scriptScore: 84,
        responseSec: 3.6,
        category: 'Стоп-лист',
        topic: 'Замена блюда из стоп-листа',
        items: [
          { name: 'Манты с бараниной', qty: 1, price: 650 },
          { name: 'Шашлык из телятины', qty: 1, price: 900 },
          { name: 'Лимонад домашний', qty: 2, price: 560 },
          { name: 'Чак-чак', qty: 1, price: 400 },
        ],
        helpRequests: 0,
        hasCue: true,
        wave: makeWave(704),
        moments: [
          { id: 'cm14', at: 20, type: 'win', title: 'Поймала стоп-лист до заказа', note: 'Подсказка Onvy сработала, гость даже не заметил, что блюда нет.' },
          { id: 'cm15', at: 42, type: 'win', title: 'Предложила равноценную замену', note: 'Манты вместо долмы — тот же формат, гость согласился сразу.' },
          { id: 'cm16', at: 78, type: 'win', title: 'Допродала десерт', note: 'Чак-чак к лимонаду — +400 ₽ к чеку.' },
        ],
        transcript: [
          { id: 'ct40', at: 18, speaker: 'client', text: 'Нам долму и шашлык из телятины.' },
          { id: 'ct41', at: 24, speaker: 'ai', text: 'Подсказка: долма в стоп-листе. Ближайшая замена — манты с бараниной, тот же формат подачи.' },
          { id: 'ct42', at: 36, speaker: 'employee', text: 'Долма сегодня, к сожалению, закончилась. Могу предложить манты с бараниной — они тоже сочные и подаются так же.', momentId: 'cm14' },
          { id: 'ct43', at: 54, speaker: 'client', text: 'Давайте манты.', momentId: 'cm15' },
          { id: 'ct44', at: 212, speaker: 'employee', text: 'К лимонаду хорошо идёт чак-чак — возьмёте на двоих?', momentId: 'cm16' },
          { id: 'ct45', at: 226, speaker: 'client', text: 'Да, давайте.' },
        ],
        summary:
          'Стоп-лист отработан правильно: замена предложена до подтверждения заказа, гость не столкнулся с отказом после ожидания. Десерт допродан.',
        recommendations: [
          'Формулировка «закончилась, могу предложить X» работает лучше, чем «этого нет». Продолжайте так же.',
        ],
      },
    ],
    tests: [
      {
        id: 'cts1',
        title: 'Аллергены и состав блюд',
        description: 'Собран по 96 вопросам гостей об аллергенах и случаям ответа по памяти.',
        source: 'errors',
        sourceDetail: 'Ошибки официантов · Аллергены',
        createdAt: '2026-07-26',
        createdBy: 'Тимур Рахимов',
        deadline: '2026-08-04',
        passScore: 90,
        questions: [
          {
            id: 'cq1',
            question: 'Гость спрашивает, есть ли в блюде орехи, и говорит про аллергию у ребёнка. Что делать?',
            options: [
              'Ответить по памяти — состав примерно известен',
              'Подтвердить состав у кухни или в карте блюда и только потом ответить',
              'Посоветовать другое блюдо, чтобы не рисковать',
              'Сказать, что точно не знаете, и отойти',
            ],
            correct: 1,
            explain: 'Аллерген — единственный случай, где догадка недопустима. Ответ даётся только после подтверждения. Отказ от ответа тоже неверен: гостю нужен факт, а не уход от вопроса.',
            source: 'Аллергены',
          },
          {
            id: 'cq2',
            question: 'Onvy показал «Информация не подтверждена». Что это значит?',
            options: [
              'Система сломалась, отвечайте сами',
              'В базе нет подтверждённых данных — нужно уточнить у кухни или менеджера',
              'Блюдо в стоп-листе',
              'Гость задал непонятный вопрос',
            ],
            correct: 1,
            explain: 'Onvy не придумывает ответ, если данных нет. Это защита гостя и ресторана: лучше уточнить, чем ошибиться на аллергене.',
            source: 'Стандарты обслуживания',
          },
          {
            id: 'cq3',
            question: 'Где быстрее всего посмотреть состав салата «Ташкент»?',
            options: [
              'Спросить у кухни',
              'В карте блюда в базе Onvy',
              'У старшего официанта',
              'В печатном меню на столе',
            ],
            correct: 1,
            explain: 'Состав есть в карте блюда. Обращение к кухне за тем, что уже есть в базе, удлиняет обслуживание втрое.',
            source: 'Состав блюд',
          },
        ],
        assignedTo: ['w3', 'w5', 'w7'],
        results: { w5: 67 },
      },
      {
        id: 'cts2',
        title: 'Стоп-лист и замены',
        description: 'Собран по 92 исправлениям заказа за месяц.',
        source: 'errors',
        sourceDetail: 'Ошибки официантов · Стоп-лист',
        createdAt: '2026-07-24',
        createdBy: 'Тимур Рахимов',
        deadline: '2026-08-02',
        passScore: 80,
        questions: [
          {
            id: 'cq4',
            question: 'Когда нужно проверять стоп-лист?',
            options: [
              'После отправки заказа на кухню',
              'До того, как подтвердить заказ гостю',
              'Только в час пик',
              'В начале смены, потом не нужно',
            ],
            correct: 1,
            explain: 'Стоп-лист меняется в течение вечера. Проверка до подтверждения убирает исправления при госте.',
            source: 'Стоп-лист',
          },
          {
            id: 'cq5',
            question: 'Гость заказал блюдо из стоп-листа. Лучшая формулировка?',
            options: [
              '«Этого нет»',
              '«Долма сегодня закончилась, могу предложить манты — тот же формат подачи»',
              '«Кухня не успевает, выберите что-то другое»',
              '«Сейчас уточню, может быть, осталось»',
            ],
            correct: 1,
            explain: 'Отказ плюс равноценная замена сохраняет заказ и не выглядит как проблема ресторана.',
            source: 'Стандарты обслуживания',
          },
        ],
        assignedTo: ['w2', 'w3', 'w5', 'w7'],
        results: { w2: 100, w5: 50 },
      },
      {
        id: 'cts3',
        title: 'Стандарт обслуживания: напиток и десерт',
        description: 'Загружен из файла «Стандарты обслуживания 2026.pdf».',
        source: 'file',
        sourceDetail: 'Файл · Стандарты обслуживания 2026.pdf',
        createdAt: '2026-06-20',
        createdBy: 'Тимур Рахимов',
        deadline: '2026-07-30',
        passScore: 70,
        questions: [
          {
            id: 'cq6',
            question: 'В какой момент предлагается напиток?',
            options: [
              'Когда гость сам попросит',
              'Каждому столу — до подтверждения основного заказа',
              'Только к горячим блюдам',
              'После подачи горячего',
            ],
            correct: 1,
            explain: 'Напиток предлагается каждому столу как этап стандарта. Норма сети — 70 % заказов.',
            source: 'Стандарты обслуживания',
          },
          {
            id: 'cq7',
            question: 'Что предложить к люля-кебабу из баранины?',
            options: ['Кофе', 'Айран или узбекский чай', 'Компот', 'Ничего, мясо самодостаточно'],
            correct: 1,
            explain: 'Айран сбивает жирность баранины. Связка даёт 71 % согласий по сети.',
            source: 'Меню',
          },
          {
            id: 'cq8',
            question: 'Когда предлагать десерт?',
            options: [
              'Вместе с основным заказом',
              'После горячего, к чаю в конце вечера',
              'Только если гость спросил',
              'На входе',
            ],
            correct: 1,
            explain: 'Чак-чак к чаю после горячего — момент максимальной готовности. Средний чек растёт на 400–800 ₽.',
            source: 'Стандарты обслуживания',
          },
        ],
        assignedTo: ['w3', 'w5', 'w7'],
        results: { w7: 100, w5: 67 },
      },
    ],
    faq: [
      {
        id: 'cf1',
        question: 'Из чего готовится это блюдо?',
        category: 'Состав блюда',
        count: 723,
        trend: 6,
        conversion: 54,
        avgResponseSec: 7.4,
        bestAnswer: 'Открыть карту блюда в Onvy и назвать состав — не уточнять у кухни, ответ уже есть в базе.',
        weakSpot: 'Рустам Ниязов, Мадина Артыкова — идут к кухне за тем, что есть в карте блюда.',
        source: 'Состав блюд',
        updatedAt: '2026-07-27',
        status: 'published',
        verified: true,
      },
      {
        id: 'cf2',
        question: 'Что посоветуете к мясу?',
        category: 'Рекомендация блюда',
        count: 474,
        trend: 9,
        conversion: 73,
        avgResponseSec: 3.1,
        bestAnswer: 'К баранине — айран или узбекский чай: сбивают жирность. Связка даёт 71 % согласий.',
        weakSpot: 'Работает хорошо. Приём Аслана Каримова стоит перенести на остальные точки.',
        source: 'Меню',
        updatedAt: '2026-07-28',
        status: 'published',
        verified: true,
      },
      {
        id: 'cf3',
        question: 'Есть ли в блюде орехи?',
        category: 'Аллергены',
        count: 288,
        trend: 17,
        conversion: 46,
        avgResponseSec: 11.2,
        bestAnswer: 'Никогда не отвечать по памяти. Подтвердить у кухни или в карте аллергенов, затем назвать факт гостю.',
        weakSpot: 'Самый рискованный вопрос сети. Санжар Убайдуллаев ответил по памяти — Onvy остановил ответ.',
        source: 'Аллергены',
        updatedAt: '2026-07-29',
        status: 'published',
        verified: true,
      },
      {
        id: 'cf4',
        question: 'Это блюдо есть сегодня?',
        category: 'Стоп-лист',
        count: 262,
        trend: 12,
        conversion: 58,
        avgResponseSec: 5.6,
        bestAnswer: 'Свериться со стоп-листом до подтверждения заказа и сразу предложить замену того же формата.',
        weakSpot: '92 исправления заказа за месяц. Парк Горького проверяет стоп-лист реже всех.',
        source: 'Стоп-лист',
        updatedAt: '2026-07-29',
        status: 'published',
        verified: true,
      },
      {
        id: 'cf5',
        question: 'Насколько блюдо острое?',
        category: 'Состав блюда',
        count: 252,
        trend: 2,
        conversion: 66,
        avgResponseSec: 6.8,
        bestAnswer: 'Уровень остроты указан в карте блюда. Плов по-фергански — не острый, средняя насыщенность специй.',
        weakSpot: 'Часть официантов уточняет у кухни, хотя данные есть в базе.',
        source: 'Состав блюд',
        updatedAt: '2026-07-12',
        status: 'published',
        verified: true,
      },
      {
        id: 'cf6',
        question: 'Сколько ждать горячее?',
        category: 'Время подачи',
        count: 186,
        trend: 4,
        conversion: 61,
        avgResponseSec: 8.9,
        bestAnswer: 'Назвать ориентир из карты блюда: плов — 20 минут, мясо гриль — 25 минут в час пик.',
        weakSpot: 'Время подачи не обновлялось с июня — данные требуют подтверждения у шеф-повара.',
        source: 'Меню',
        updatedAt: '2026-06-08',
        status: 'outdated',
        verified: false,
      },
      {
        id: 'cf7',
        question: 'Есть ли вегетарианские блюда?',
        category: 'Состав блюда',
        count: 148,
        trend: 8,
        conversion: 64,
        avgResponseSec: 5.2,
        bestAnswer: 'Назвать три позиции: салат «Ташкент» без мяса, лепёшка тандырная, овощи гриль.',
        weakSpot: 'Черновик: список не согласован с кухней, публиковать рано.',
        source: 'Меню',
        updatedAt: '2026-07-29',
        status: 'draft',
        verified: false,
      },
    ],
    scriptErrors: [
      { id: 'cse1', label: 'Ответ по составу без проверки', count: 214, costPerMonth: 0, employees: ['Санжар Убайдуллаев', 'Рустам Ниязов', 'Мадина Артыкова'] },
      { id: 'cse2', label: 'Не проверил стоп-лист', count: 92, costPerMonth: 0, employees: ['Санжар Убайдуллаев', 'Рустам Ниязов'] },
      { id: 'cse3', label: 'Не предложен напиток', count: 386, costPerMonth: 0, employees: ['Санжар Убайдуллаев', 'Рустам Ниязов', 'Мадина Артыкова'] },
      { id: 'cse4', label: 'Не предложен десерт', count: 512, costPerMonth: 0, employees: ['Санжар Убайдуллаев', 'Рустам Ниязов', 'Мадина Артыкова', 'Алина Юсупова'] },
      { id: 'cse5', label: 'Не уточнил аллергены', count: 41, costPerMonth: 0, employees: ['Санжар Убайдуллаев'] },
      { id: 'cse6', label: 'Заказ подтверждён с ошибкой', count: 131, costPerMonth: 0, employees: ['Рустам Ниязов', 'Мадина Артыкова', 'Санжар Убайдуллаев'] },
    ],
    knowledgeFiles: [
      { id: 'ckf1', name: 'Меню_лето_2026.pdf', sizeKb: 1_240, uploadedAt: '2026-06-01', kind: 'menu', categories: ['Горячее', 'Салаты', 'Напитки', 'Десерты'], records: 184 },
      { id: 'ckf2', name: 'Технологические_карты.xlsx', sizeKb: 664, uploadedAt: '2026-06-02', kind: 'composition', categories: ['Состав', 'Выход блюда', 'Острота'], records: 184 },
      { id: 'ckf3', name: 'Аллергены_матрица.xlsx', sizeKb: 148, uploadedAt: '2026-06-02', kind: 'allergens', categories: ['Орехи', 'Глютен', 'Молочное', 'Специи'], records: 184 },
      { id: 'ckf4', name: 'Стоп-лист (обновляется)', sizeKb: 12, uploadedAt: '2026-07-29', kind: 'stoplist', categories: ['Стоп-лист смены'], records: 9 },
      { id: 'ckf5', name: 'Стандарты обслуживания 2026.pdf', sizeKb: 320, uploadedAt: '2026-06-03', kind: 'standards', categories: ['Шаги сервиса', 'Допродажи'], records: 32 },
    ],
    pilot: {
      startedAt: '2026-06-15',
      weeks: 6,
      scope: '3 ресторана · 7 официантов',
      goals: [
        'Сократить срок выхода новичка на самостоятельную смену',
        'Поднять единообразие стандарта обслуживания между ресторанами',
        'Убрать ответы по составу и аллергенам «по памяти»',
        'Распространить удачные практики сильных официантов',
      ],
      metrics: [
        { key: 'responseSec', label: 'Скорость ответа гостю', before: 9.1, during: 5.4, unit: 'sec', better: 'down' },
        { key: 'autonomy', label: 'Решено самостоятельно', before: 52, during: 75, unit: 'pct', better: 'up' },
        { key: 'kitchenEscalations', label: 'Обращения к кухне и менеджеру', before: 1_142, during: 678, unit: 'count', better: 'down' },
        { key: 'scriptCompliance', label: 'Выполнение стандарта обслуживания', before: 64, during: 82, unit: 'pct', better: 'up' },
        { key: 'orderCorrections', label: 'Исправления заказа', before: 246, during: 153, unit: 'count', better: 'down' },
        { key: 'training', label: 'Прогресс обучения', before: 28, during: 75, unit: 'pct', better: 'up' },
        { key: 'badgeCoverage', label: 'Покрытие бейджами', before: 0, during: 86, unit: 'pct', better: 'up' },
        { key: 'drinkOffer', label: 'Предложен напиток', before: 44, during: 65, unit: 'pct', better: 'up' },
        { key: 'avgCheck', label: 'Средний чек', before: 2_840, during: 3_210, unit: 'money', better: 'up', external: true },
      ],
    },
    adaptation: {
      daysToSolo: 11,
      daysToSoloBefore: 32,
      requiredModules: 3,
      completion: 74,
      firstCheckScore: 62,
      repeatedErrors: 14,
      noviceHelpPerShift: 6.2,
      earlyCompliance: 68,
    },
    bestPractices: [
      {
        id: 'bp1',
        employeeId: 'w1',
        pointId: 'r1',
        title: 'Проверка стоп-листа до рекомендации',
        quote: 'Рекомендую люля из баранины и каре ягнёнка. Оба блюда сегодня есть, я проверил.',
        effect: 'Ни одного исправления заказа за месяц против 53 у коллег с тем же потоком.',
        category: 'Стоп-лист',
        dialogId: 'cd2',
        inTraining: true,
      },
      {
        id: 'bp2',
        employeeId: 'w1',
        pointId: 'r1',
        title: 'Подтверждение состава при вопросе об аллергене',
        quote: 'По аллергенам отвечаю только точно — секунду, уточню у кухни.',
        effect: 'Ноль ответов по памяти на вопрос об аллергене. Практика внесена в обязательный модуль.',
        category: 'Аллергены',
        inTraining: true,
      },
      {
        id: 'bp3',
        employeeId: 'w2',
        pointId: 'r1',
        title: 'Отказ с равноценной заменой',
        quote: 'Долма сегодня закончилась, могу предложить манты — тот же формат подачи.',
        effect: 'Гость почти всегда соглашается: заказ сохраняется, отказ не выглядит проблемой ресторана.',
        category: 'Стоп-лист',
        dialogId: 'cd4',
        inTraining: false,
      },
      {
        id: 'bp4',
        employeeId: 'w6',
        pointId: 'r3',
        title: 'Напиток как часть рекомендации к мясу',
        quote: 'К баранине очень хорошо идёт айран — он сбивает жирность.',
        effect: 'Средний чек 3 579 ₽ — лучший в сети. Формулировка объясняет пользу, а не продаёт.',
        category: 'Рекомендация блюда',
        inTraining: false,
      },
    ],
    trainingOutcomes: [
      {
        testId: 'cts1',
        reason: 'Ответы по составу и аллергенам без проверки — 214 случаев за месяц',
        origin: 'Разбор обслуживаний · категория «Аллергены»',
        metric: 'allergenAccuracy',
        metricLabel: 'Ответы по аллергенам с подтверждением',
        before: 41,
        after: 78,
        unit: 'pct',
        better: 'up',
        repeated: true,
      },
      {
        testId: 'cts2',
        reason: '92 исправления заказа из-за непроверенного стоп-листа',
        origin: 'Разбор обслуживаний · категория «Стоп-лист»',
        metric: 'orderCorrections',
        metricLabel: 'Исправления заказа',
        before: 92,
        after: 51,
        unit: 'count',
        better: 'down',
        repeated: false,
      },
      {
        testId: 'cts3',
        reason: 'Напиток предлагался только в 44 % заказов при норме 70 %',
        origin: 'Стандарты обслуживания · загруженный документ',
        metric: 'drinkOffer',
        metricLabel: 'Предложен напиток',
        before: 44,
        after: 65,
        unit: 'pct',
        better: 'up',
        repeated: false,
      },
    ],
  };
}
